# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ton/trace_message.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'ton/trace_message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ton import block_message_pb2 as ton_dot_block__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17ton/trace_message.proto\x12\x0cton_messages\x1a\x17ton/block_message.proto\"\x9d\x01\n\x05Trace\x12.\n\x0b\x42lockHeader\x18\x01 \x01(\x0b\x32\x19.ton_messages.BlockHeader\x12.\n\x0bTransaction\x18\x02 \x01(\x0b\x32\x19.ton_messages.Transaction\x12\r\n\x05\x44\x65pth\x18\x03 \x01(\r\x12%\n\x08\x43hildren\x18\x04 \x03(\x0b\x32\x13.ton_messages.Trace\"W\n\x0cTraceMessage\x12\"\n\x05\x43hain\x18\x01 \x01(\x0b\x32\x13.ton_messages.Chain\x12#\n\x06Traces\x18\x02 \x03(\x0b\x32\x13.ton_messages.Traceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ton.trace_message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACE']._serialized_start=67
  _globals['_TRACE']._serialized_end=224
  _globals['_TRACEMESSAGE']._serialized_start=226
  _globals['_TRACEMESSAGE']._serialized_end=313
# @@protoc_insertion_point(module_scope)
