// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hyperliquid/candles.proto

package hyperliquid_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TimeInterval identifies a candle bucket. All values are epoch SECONDS (not ns) to
// match toStartOfInterval semantics; Duration is the bucket width in seconds
// (60/300/900/3600 = 1m/5m/15m/1h).
type TimeInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      uint32                 `protobuf:"varint,1,opt,name=Duration,proto3" json:"Duration,omitempty"` // bucket width, seconds
	Start         uint32                 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`       // bar open, epoch seconds (toStartOfInterval)
	End           uint32                 `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`           // bar close boundary, epoch seconds (Start + Duration)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeInterval) Reset() {
	*x = TimeInterval{}
	mi := &file_hyperliquid_candles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInterval) ProtoMessage() {}

func (x *TimeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_candles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInterval.ProtoReflect.Descriptor instead.
func (*TimeInterval) Descriptor() ([]byte, []int) {
	return file_hyperliquid_candles_proto_rawDescGZIP(), []int{0}
}

func (x *TimeInterval) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TimeInterval) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeInterval) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

// Ohlc carries the price/volume aggregates of one bar. double (Float64) so high-priced
// assets (e.g. BTC ~100k) keep full precision — float32 would lose the low digits.
type Ohlc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float64                `protobuf:"fixed64,1,opt,name=Open,proto3" json:"Open,omitempty"`
	High          float64                `protobuf:"fixed64,2,opt,name=High,proto3" json:"High,omitempty"`
	Low           float64                `protobuf:"fixed64,3,opt,name=Low,proto3" json:"Low,omitempty"`
	Close         float64                `protobuf:"fixed64,4,opt,name=Close,proto3" json:"Close,omitempty"`
	Volume        float64                `protobuf:"fixed64,5,opt,name=Volume,proto3" json:"Volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ohlc) Reset() {
	*x = Ohlc{}
	mi := &file_hyperliquid_candles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ohlc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ohlc) ProtoMessage() {}

func (x *Ohlc) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_candles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ohlc.ProtoReflect.Descriptor instead.
func (*Ohlc) Descriptor() ([]byte, []int) {
	return file_hyperliquid_candles_proto_rawDescGZIP(), []int{1}
}

func (x *Ohlc) GetOpen() float64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Ohlc) GetHigh() float64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Ohlc) GetLow() float64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Ohlc) GetClose() float64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Ohlc) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// Candle is one OHLC bar for one market at one interval width.
type Candle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Market        *Market                `protobuf:"bytes,1,opt,name=Market,proto3" json:"Market,omitempty"` // shared hyperliquid_messages.Market
	Interval      *TimeInterval          `protobuf:"bytes,2,opt,name=Interval,proto3" json:"Interval,omitempty"`
	Ohlc          *Ohlc                  `protobuf:"bytes,3,opt,name=Ohlc,proto3" json:"Ohlc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Candle) Reset() {
	*x = Candle{}
	mi := &file_hyperliquid_candles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Candle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Candle) ProtoMessage() {}

func (x *Candle) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_candles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Candle.ProtoReflect.Descriptor instead.
func (*Candle) Descriptor() ([]byte, []int) {
	return file_hyperliquid_candles_proto_rawDescGZIP(), []int{2}
}

func (x *Candle) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *Candle) GetInterval() *TimeInterval {
	if x != nil {
		return x.Interval
	}
	return nil
}

func (x *Candle) GetOhlc() *Ohlc {
	if x != nil {
		return x.Ohlc
	}
	return nil
}

// CandlesBlockMessage batches the bars touched by one trades block, mirroring the
// TradesBlockMessage envelope (BlockNumber + epoch-ns BlockTime + repeated payload).
type CandlesBlockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber   uint64                 `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime     int64                  `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"` // epoch ns
	Candles       []*Candle              `protobuf:"bytes,3,rep,name=Candles,proto3" json:"Candles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CandlesBlockMessage) Reset() {
	*x = CandlesBlockMessage{}
	mi := &file_hyperliquid_candles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CandlesBlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CandlesBlockMessage) ProtoMessage() {}

func (x *CandlesBlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_candles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CandlesBlockMessage.ProtoReflect.Descriptor instead.
func (*CandlesBlockMessage) Descriptor() ([]byte, []int) {
	return file_hyperliquid_candles_proto_rawDescGZIP(), []int{3}
}

func (x *CandlesBlockMessage) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *CandlesBlockMessage) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *CandlesBlockMessage) GetCandles() []*Candle {
	if x != nil {
		return x.Candles
	}
	return nil
}

var File_hyperliquid_candles_proto protoreflect.FileDescriptor

const file_hyperliquid_candles_proto_rawDesc = "" +
	"\n" +
	"\x19hyperliquid/candles.proto\x12\x14hyperliquid_messages\x1a+hyperliquid/hyperliquid_block_message.proto\"R\n" +
	"\fTimeInterval\x12\x1a\n" +
	"\bDuration\x18\x01 \x01(\rR\bDuration\x12\x14\n" +
	"\x05Start\x18\x02 \x01(\rR\x05Start\x12\x10\n" +
	"\x03End\x18\x03 \x01(\rR\x03End\"n\n" +
	"\x04Ohlc\x12\x12\n" +
	"\x04Open\x18\x01 \x01(\x01R\x04Open\x12\x12\n" +
	"\x04High\x18\x02 \x01(\x01R\x04High\x12\x10\n" +
	"\x03Low\x18\x03 \x01(\x01R\x03Low\x12\x14\n" +
	"\x05Close\x18\x04 \x01(\x01R\x05Close\x12\x16\n" +
	"\x06Volume\x18\x05 \x01(\x01R\x06Volume\"\xae\x01\n" +
	"\x06Candle\x124\n" +
	"\x06Market\x18\x01 \x01(\v2\x1c.hyperliquid_messages.MarketR\x06Market\x12>\n" +
	"\bInterval\x18\x02 \x01(\v2\".hyperliquid_messages.TimeIntervalR\bInterval\x12.\n" +
	"\x04Ohlc\x18\x03 \x01(\v2\x1a.hyperliquid_messages.OhlcR\x04Ohlc\"\x8d\x01\n" +
	"\x13CandlesBlockMessage\x12 \n" +
	"\vBlockNumber\x18\x01 \x01(\x04R\vBlockNumber\x12\x1c\n" +
	"\tBlockTime\x18\x02 \x01(\x03R\tBlockTime\x126\n" +
	"\aCandles\x18\x03 \x03(\v2\x1c.hyperliquid_messages.CandleR\aCandlesb\x06proto3"

var (
	file_hyperliquid_candles_proto_rawDescOnce sync.Once
	file_hyperliquid_candles_proto_rawDescData []byte
)

func file_hyperliquid_candles_proto_rawDescGZIP() []byte {
	file_hyperliquid_candles_proto_rawDescOnce.Do(func() {
		file_hyperliquid_candles_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperliquid_candles_proto_rawDesc), len(file_hyperliquid_candles_proto_rawDesc)))
	})
	return file_hyperliquid_candles_proto_rawDescData
}

var file_hyperliquid_candles_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hyperliquid_candles_proto_goTypes = []any{
	(*TimeInterval)(nil),        // 0: hyperliquid_messages.TimeInterval
	(*Ohlc)(nil),                // 1: hyperliquid_messages.Ohlc
	(*Candle)(nil),              // 2: hyperliquid_messages.Candle
	(*CandlesBlockMessage)(nil), // 3: hyperliquid_messages.CandlesBlockMessage
	(*Market)(nil),              // 4: hyperliquid_messages.Market
}
var file_hyperliquid_candles_proto_depIdxs = []int32{
	4, // 0: hyperliquid_messages.Candle.Market:type_name -> hyperliquid_messages.Market
	0, // 1: hyperliquid_messages.Candle.Interval:type_name -> hyperliquid_messages.TimeInterval
	1, // 2: hyperliquid_messages.Candle.Ohlc:type_name -> hyperliquid_messages.Ohlc
	2, // 3: hyperliquid_messages.CandlesBlockMessage.Candles:type_name -> hyperliquid_messages.Candle
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_hyperliquid_candles_proto_init() }
func file_hyperliquid_candles_proto_init() {
	if File_hyperliquid_candles_proto != nil {
		return
	}
	file_hyperliquid_hyperliquid_block_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperliquid_candles_proto_rawDesc), len(file_hyperliquid_candles_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hyperliquid_candles_proto_goTypes,
		DependencyIndexes: file_hyperliquid_candles_proto_depIdxs,
		MessageInfos:      file_hyperliquid_candles_proto_msgTypes,
	}.Build()
	File_hyperliquid_candles_proto = out.File
	file_hyperliquid_candles_proto_goTypes = nil
	file_hyperliquid_candles_proto_depIdxs = nil
}
