// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: hyperliquid/hypercore.proto

package hyperliquid_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HyperCoreBlock struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber       uint64                 `protobuf:"varint,1,opt,name=BlockNumber,proto3" json:"BlockNumber,omitempty"`
	BlockTime         int64                  `protobuf:"varint,2,opt,name=BlockTime,proto3" json:"BlockTime,omitempty"` // consensus block time, epoch NANOSECONDS (UTC) — shared by all events
	Fills             []*Fill                `protobuf:"bytes,3,rep,name=Fills,proto3" json:"Fills,omitempty"`
	OrderStatuses     []*OrderStatus         `protobuf:"bytes,4,rep,name=OrderStatuses,proto3" json:"OrderStatuses,omitempty"`
	BookDiffs         []*BookDiff            `protobuf:"bytes,5,rep,name=BookDiffs,proto3" json:"BookDiffs,omitempty"`
	TwapStatuses      []*TwapStatus          `protobuf:"bytes,6,rep,name=TwapStatuses,proto3" json:"TwapStatuses,omitempty"`
	OracleUpdates     []*OracleUpdate        `protobuf:"bytes,7,rep,name=OracleUpdates,proto3" json:"OracleUpdates,omitempty"`
	MiscEvents        []*MiscEvent           `protobuf:"bytes,8,rep,name=MiscEvents,proto3" json:"MiscEvents,omitempty"`
	CoreWriterActions []*SystemAction        `protobuf:"bytes,9,rep,name=CoreWriterActions,proto3" json:"CoreWriterActions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HyperCoreBlock) Reset() {
	*x = HyperCoreBlock{}
	mi := &file_hyperliquid_hypercore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperCoreBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperCoreBlock) ProtoMessage() {}

func (x *HyperCoreBlock) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_hypercore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperCoreBlock.ProtoReflect.Descriptor instead.
func (*HyperCoreBlock) Descriptor() ([]byte, []int) {
	return file_hyperliquid_hypercore_proto_rawDescGZIP(), []int{0}
}

func (x *HyperCoreBlock) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *HyperCoreBlock) GetBlockTime() int64 {
	if x != nil {
		return x.BlockTime
	}
	return 0
}

func (x *HyperCoreBlock) GetFills() []*Fill {
	if x != nil {
		return x.Fills
	}
	return nil
}

func (x *HyperCoreBlock) GetOrderStatuses() []*OrderStatus {
	if x != nil {
		return x.OrderStatuses
	}
	return nil
}

func (x *HyperCoreBlock) GetBookDiffs() []*BookDiff {
	if x != nil {
		return x.BookDiffs
	}
	return nil
}

func (x *HyperCoreBlock) GetTwapStatuses() []*TwapStatus {
	if x != nil {
		return x.TwapStatuses
	}
	return nil
}

func (x *HyperCoreBlock) GetOracleUpdates() []*OracleUpdate {
	if x != nil {
		return x.OracleUpdates
	}
	return nil
}

func (x *HyperCoreBlock) GetMiscEvents() []*MiscEvent {
	if x != nil {
		return x.MiscEvents
	}
	return nil
}

func (x *HyperCoreBlock) GetCoreWriterActions() []*SystemAction {
	if x != nil {
		return x.CoreWriterActions
	}
	return nil
}

type HyperCoreBlocks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Blocks        []*HyperCoreBlock      `protobuf:"bytes,1,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HyperCoreBlocks) Reset() {
	*x = HyperCoreBlocks{}
	mi := &file_hyperliquid_hypercore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HyperCoreBlocks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HyperCoreBlocks) ProtoMessage() {}

func (x *HyperCoreBlocks) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_hypercore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HyperCoreBlocks.ProtoReflect.Descriptor instead.
func (*HyperCoreBlocks) Descriptor() ([]byte, []int) {
	return file_hyperliquid_hypercore_proto_rawDescGZIP(), []int{1}
}

func (x *HyperCoreBlocks) GetBlocks() []*HyperCoreBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_hyperliquid_hypercore_proto protoreflect.FileDescriptor

const file_hyperliquid_hypercore_proto_rawDesc = "" +
	"\n" +
	"\x1bhyperliquid/hypercore.proto\x12\x14hyperliquid_messages\x1a\x17hyperliquid/fills.proto\x1a hyperliquid/order_statuses.proto\x1a hyperliquid/raw_book_diffs.proto\x1a\x1fhyperliquid/twap_statuses.proto\x1a hyperliquid/oracle_updates.proto\x1a\x1dhyperliquid/misc_events.proto\x1a%hyperliquid/core_writer_actions.proto\"\xac\x04\n" +
	"\x0eHyperCoreBlock\x12 \n" +
	"\vBlockNumber\x18\x01 \x01(\x04R\vBlockNumber\x12\x1c\n" +
	"\tBlockTime\x18\x02 \x01(\x03R\tBlockTime\x120\n" +
	"\x05Fills\x18\x03 \x03(\v2\x1a.hyperliquid_messages.FillR\x05Fills\x12G\n" +
	"\rOrderStatuses\x18\x04 \x03(\v2!.hyperliquid_messages.OrderStatusR\rOrderStatuses\x12<\n" +
	"\tBookDiffs\x18\x05 \x03(\v2\x1e.hyperliquid_messages.BookDiffR\tBookDiffs\x12D\n" +
	"\fTwapStatuses\x18\x06 \x03(\v2 .hyperliquid_messages.TwapStatusR\fTwapStatuses\x12H\n" +
	"\rOracleUpdates\x18\a \x03(\v2\".hyperliquid_messages.OracleUpdateR\rOracleUpdates\x12?\n" +
	"\n" +
	"MiscEvents\x18\b \x03(\v2\x1f.hyperliquid_messages.MiscEventR\n" +
	"MiscEvents\x12P\n" +
	"\x11CoreWriterActions\x18\t \x03(\v2\".hyperliquid_messages.SystemActionR\x11CoreWriterActions\"O\n" +
	"\x0fHyperCoreBlocks\x12<\n" +
	"\x06Blocks\x18\x01 \x03(\v2$.hyperliquid_messages.HyperCoreBlockR\x06Blocksb\x06proto3"

var (
	file_hyperliquid_hypercore_proto_rawDescOnce sync.Once
	file_hyperliquid_hypercore_proto_rawDescData []byte
)

func file_hyperliquid_hypercore_proto_rawDescGZIP() []byte {
	file_hyperliquid_hypercore_proto_rawDescOnce.Do(func() {
		file_hyperliquid_hypercore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperliquid_hypercore_proto_rawDesc), len(file_hyperliquid_hypercore_proto_rawDesc)))
	})
	return file_hyperliquid_hypercore_proto_rawDescData
}

var file_hyperliquid_hypercore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hyperliquid_hypercore_proto_goTypes = []any{
	(*HyperCoreBlock)(nil),  // 0: hyperliquid_messages.HyperCoreBlock
	(*HyperCoreBlocks)(nil), // 1: hyperliquid_messages.HyperCoreBlocks
	(*Fill)(nil),            // 2: hyperliquid_messages.Fill
	(*OrderStatus)(nil),     // 3: hyperliquid_messages.OrderStatus
	(*BookDiff)(nil),        // 4: hyperliquid_messages.BookDiff
	(*TwapStatus)(nil),      // 5: hyperliquid_messages.TwapStatus
	(*OracleUpdate)(nil),    // 6: hyperliquid_messages.OracleUpdate
	(*MiscEvent)(nil),       // 7: hyperliquid_messages.MiscEvent
	(*SystemAction)(nil),    // 8: hyperliquid_messages.SystemAction
}
var file_hyperliquid_hypercore_proto_depIdxs = []int32{
	2, // 0: hyperliquid_messages.HyperCoreBlock.Fills:type_name -> hyperliquid_messages.Fill
	3, // 1: hyperliquid_messages.HyperCoreBlock.OrderStatuses:type_name -> hyperliquid_messages.OrderStatus
	4, // 2: hyperliquid_messages.HyperCoreBlock.BookDiffs:type_name -> hyperliquid_messages.BookDiff
	5, // 3: hyperliquid_messages.HyperCoreBlock.TwapStatuses:type_name -> hyperliquid_messages.TwapStatus
	6, // 4: hyperliquid_messages.HyperCoreBlock.OracleUpdates:type_name -> hyperliquid_messages.OracleUpdate
	7, // 5: hyperliquid_messages.HyperCoreBlock.MiscEvents:type_name -> hyperliquid_messages.MiscEvent
	8, // 6: hyperliquid_messages.HyperCoreBlock.CoreWriterActions:type_name -> hyperliquid_messages.SystemAction
	0, // 7: hyperliquid_messages.HyperCoreBlocks.Blocks:type_name -> hyperliquid_messages.HyperCoreBlock
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_hyperliquid_hypercore_proto_init() }
func file_hyperliquid_hypercore_proto_init() {
	if File_hyperliquid_hypercore_proto != nil {
		return
	}
	file_hyperliquid_fills_proto_init()
	file_hyperliquid_order_statuses_proto_init()
	file_hyperliquid_raw_book_diffs_proto_init()
	file_hyperliquid_twap_statuses_proto_init()
	file_hyperliquid_oracle_updates_proto_init()
	file_hyperliquid_misc_events_proto_init()
	file_hyperliquid_core_writer_actions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperliquid_hypercore_proto_rawDesc), len(file_hyperliquid_hypercore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hyperliquid_hypercore_proto_goTypes,
		DependencyIndexes: file_hyperliquid_hypercore_proto_depIdxs,
		MessageInfos:      file_hyperliquid_hypercore_proto_msgTypes,
	}.Build()
	File_hyperliquid_hypercore_proto = out.File
	file_hyperliquid_hypercore_proto_goTypes = nil
	file_hyperliquid_hypercore_proto_depIdxs = nil
}
