// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: hyperliquid/raw_book_diffs.proto

// Canonical HyperCore schema for Bitquery streaming — node_raw_book_diffs stream (L4 deltas).

package hyperliquid_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BookDiff = one L4 order-book delta from node_raw_book_diffs_streaming.
// The node's `raw_book_diff` is a tagged union we flatten into Kind + variant fields:
//
//	{"new":{"sz":..}}                  → Kind="new",    Sz set
//	{"update":{"origSz":..,"newSz":..}}→ Kind="update", OrigSz+NewSz set
//	"remove"                            → Kind="remove", size fields unset
//
// Kind is set to the union tag verbatim, so an unseen variant is still preserved.
type BookDiff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          []byte                 `protobuf:"bytes,1,opt,name=User,proto3" json:"User,omitempty"` // 0x-address that owns the order
	Oid           uint64                 `protobuf:"varint,2,opt,name=Oid,proto3" json:"Oid,omitempty"`  // order id
	Coin          string                 `protobuf:"bytes,3,opt,name=Coin,proto3" json:"Coin,omitempty"`
	Side          string                 `protobuf:"bytes,4,opt,name=Side,proto3" json:"Side,omitempty"`           // "B"=bid, "A"=ask. LowCardinality
	Px            string                 `protobuf:"bytes,5,opt,name=Px,proto3" json:"Px,omitempty"`               // price level
	Kind          string                 `protobuf:"bytes,6,opt,name=Kind,proto3" json:"Kind,omitempty"`           // "new" | "update" | "remove". LowCardinality
	Sz            *string                `protobuf:"bytes,7,opt,name=Sz,proto3,oneof" json:"Sz,omitempty"`         // Kind="new": resting size at this level
	OrigSz        *string                `protobuf:"bytes,8,opt,name=OrigSz,proto3,oneof" json:"OrigSz,omitempty"` // Kind="update": size before
	NewSz         *string                `protobuf:"bytes,9,opt,name=NewSz,proto3,oneof" json:"NewSz,omitempty"`   // Kind="update": size after
	Extra         map[string]string      `protobuf:"bytes,10,rep,name=Extra,proto3" json:"Extra,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookDiff) Reset() {
	*x = BookDiff{}
	mi := &file_hyperliquid_raw_book_diffs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookDiff) ProtoMessage() {}

func (x *BookDiff) ProtoReflect() protoreflect.Message {
	mi := &file_hyperliquid_raw_book_diffs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookDiff.ProtoReflect.Descriptor instead.
func (*BookDiff) Descriptor() ([]byte, []int) {
	return file_hyperliquid_raw_book_diffs_proto_rawDescGZIP(), []int{0}
}

func (x *BookDiff) GetUser() []byte {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *BookDiff) GetOid() uint64 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *BookDiff) GetCoin() string {
	if x != nil {
		return x.Coin
	}
	return ""
}

func (x *BookDiff) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *BookDiff) GetPx() string {
	if x != nil {
		return x.Px
	}
	return ""
}

func (x *BookDiff) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *BookDiff) GetSz() string {
	if x != nil && x.Sz != nil {
		return *x.Sz
	}
	return ""
}

func (x *BookDiff) GetOrigSz() string {
	if x != nil && x.OrigSz != nil {
		return *x.OrigSz
	}
	return ""
}

func (x *BookDiff) GetNewSz() string {
	if x != nil && x.NewSz != nil {
		return *x.NewSz
	}
	return ""
}

func (x *BookDiff) GetExtra() map[string]string {
	if x != nil {
		return x.Extra
	}
	return nil
}

var File_hyperliquid_raw_book_diffs_proto protoreflect.FileDescriptor

const file_hyperliquid_raw_book_diffs_proto_rawDesc = "" +
	"\n" +
	" hyperliquid/raw_book_diffs.proto\x12\x14hyperliquid_messages\"\xe0\x02\n" +
	"\bBookDiff\x12\x12\n" +
	"\x04User\x18\x01 \x01(\fR\x04User\x12\x10\n" +
	"\x03Oid\x18\x02 \x01(\x04R\x03Oid\x12\x12\n" +
	"\x04Coin\x18\x03 \x01(\tR\x04Coin\x12\x12\n" +
	"\x04Side\x18\x04 \x01(\tR\x04Side\x12\x0e\n" +
	"\x02Px\x18\x05 \x01(\tR\x02Px\x12\x12\n" +
	"\x04Kind\x18\x06 \x01(\tR\x04Kind\x12\x13\n" +
	"\x02Sz\x18\a \x01(\tH\x00R\x02Sz\x88\x01\x01\x12\x1b\n" +
	"\x06OrigSz\x18\b \x01(\tH\x01R\x06OrigSz\x88\x01\x01\x12\x19\n" +
	"\x05NewSz\x18\t \x01(\tH\x02R\x05NewSz\x88\x01\x01\x12?\n" +
	"\x05Extra\x18\n" +
	" \x03(\v2).hyperliquid_messages.BookDiff.ExtraEntryR\x05Extra\x1a8\n" +
	"\n" +
	"ExtraEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01B\x05\n" +
	"\x03_SzB\t\n" +
	"\a_OrigSzB\b\n" +
	"\x06_NewSzb\x06proto3"

var (
	file_hyperliquid_raw_book_diffs_proto_rawDescOnce sync.Once
	file_hyperliquid_raw_book_diffs_proto_rawDescData []byte
)

func file_hyperliquid_raw_book_diffs_proto_rawDescGZIP() []byte {
	file_hyperliquid_raw_book_diffs_proto_rawDescOnce.Do(func() {
		file_hyperliquid_raw_book_diffs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hyperliquid_raw_book_diffs_proto_rawDesc), len(file_hyperliquid_raw_book_diffs_proto_rawDesc)))
	})
	return file_hyperliquid_raw_book_diffs_proto_rawDescData
}

var file_hyperliquid_raw_book_diffs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_hyperliquid_raw_book_diffs_proto_goTypes = []any{
	(*BookDiff)(nil), // 0: hyperliquid_messages.BookDiff
	nil,              // 1: hyperliquid_messages.BookDiff.ExtraEntry
}
var file_hyperliquid_raw_book_diffs_proto_depIdxs = []int32{
	1, // 0: hyperliquid_messages.BookDiff.Extra:type_name -> hyperliquid_messages.BookDiff.ExtraEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hyperliquid_raw_book_diffs_proto_init() }
func file_hyperliquid_raw_book_diffs_proto_init() {
	if File_hyperliquid_raw_book_diffs_proto != nil {
		return
	}
	file_hyperliquid_raw_book_diffs_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hyperliquid_raw_book_diffs_proto_rawDesc), len(file_hyperliquid_raw_book_diffs_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_hyperliquid_raw_book_diffs_proto_goTypes,
		DependencyIndexes: file_hyperliquid_raw_book_diffs_proto_depIdxs,
		MessageInfos:      file_hyperliquid_raw_book_diffs_proto_msgTypes,
	}.Build()
	File_hyperliquid_raw_book_diffs_proto = out.File
	file_hyperliquid_raw_book_diffs_proto_goTypes = nil
	file_hyperliquid_raw_book_diffs_proto_depIdxs = nil
}
