// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: tron/parsed_abi_block_message.proto

package tron_messages

import (
	messages "github.com/bitquery/streaming_protobuf/v2/evm/messages"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContractInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=Type,proto3" json:"Type,omitempty"`
	TypeUrl       string                 `protobuf:"bytes,3,opt,name=TypeUrl,proto3" json:"TypeUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContractInfo) Reset() {
	*x = ContractInfo{}
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContractInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractInfo) ProtoMessage() {}

func (x *ContractInfo) ProtoReflect() protoreflect.Message {
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractInfo.ProtoReflect.Descriptor instead.
func (*ContractInfo) Descriptor() ([]byte, []int) {
	return file_tron_parsed_abi_block_message_proto_rawDescGZIP(), []int{0}
}

func (x *ContractInfo) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ContractInfo) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ContractInfo) GetTypeUrl() string {
	if x != nil {
		return x.TypeUrl
	}
	return ""
}

type ParsedAbiTransaction struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	TransactionHeader *TransactionHeader                   `protobuf:"bytes,1,opt,name=TransactionHeader,proto3" json:"TransactionHeader,omitempty"`
	Receipt           *Receipt                             `protobuf:"bytes,2,opt,name=Receipt,proto3" json:"Receipt,omitempty"`
	TransactionStatus *messages.ParsedAbiTransactionStatus `protobuf:"bytes,3,opt,name=TransactionStatus,proto3" json:"TransactionStatus,omitempty"`
	TransactionResult *TransactionResult                   `protobuf:"bytes,4,opt,name=TransactionResult,proto3" json:"TransactionResult,omitempty"`
	ContractInfo      *ContractInfo                        `protobuf:"bytes,5,opt,name=ContractInfo,proto3" json:"ContractInfo,omitempty"`
	Calls             []*messages.ParsedAbiCall            `protobuf:"bytes,6,rep,name=Calls,proto3" json:"Calls,omitempty"`
	RewardWithdraw    *RewardWithdraw                      `protobuf:"bytes,7,opt,name=RewardWithdraw,proto3" json:"RewardWithdraw,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParsedAbiTransaction) Reset() {
	*x = ParsedAbiTransaction{}
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiTransaction) ProtoMessage() {}

func (x *ParsedAbiTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiTransaction.ProtoReflect.Descriptor instead.
func (*ParsedAbiTransaction) Descriptor() ([]byte, []int) {
	return file_tron_parsed_abi_block_message_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedAbiTransaction) GetTransactionHeader() *TransactionHeader {
	if x != nil {
		return x.TransactionHeader
	}
	return nil
}

func (x *ParsedAbiTransaction) GetReceipt() *Receipt {
	if x != nil {
		return x.Receipt
	}
	return nil
}

func (x *ParsedAbiTransaction) GetTransactionStatus() *messages.ParsedAbiTransactionStatus {
	if x != nil {
		return x.TransactionStatus
	}
	return nil
}

func (x *ParsedAbiTransaction) GetTransactionResult() *TransactionResult {
	if x != nil {
		return x.TransactionResult
	}
	return nil
}

func (x *ParsedAbiTransaction) GetContractInfo() *ContractInfo {
	if x != nil {
		return x.ContractInfo
	}
	return nil
}

func (x *ParsedAbiTransaction) GetCalls() []*messages.ParsedAbiCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *ParsedAbiTransaction) GetRewardWithdraw() *RewardWithdraw {
	if x != nil {
		return x.RewardWithdraw
	}
	return nil
}

type ParsedAbiBlockMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Chain         *Chain                  `protobuf:"bytes,1,opt,name=Chain,proto3" json:"Chain,omitempty"`
	Header        *BlockHeader            `protobuf:"bytes,2,opt,name=Header,proto3" json:"Header,omitempty"`
	Witness       *Witness                `protobuf:"bytes,3,opt,name=Witness,proto3" json:"Witness,omitempty"`
	Transactions  []*ParsedAbiTransaction `protobuf:"bytes,4,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiBlockMessage) Reset() {
	*x = ParsedAbiBlockMessage{}
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiBlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiBlockMessage) ProtoMessage() {}

func (x *ParsedAbiBlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_tron_parsed_abi_block_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiBlockMessage.ProtoReflect.Descriptor instead.
func (*ParsedAbiBlockMessage) Descriptor() ([]byte, []int) {
	return file_tron_parsed_abi_block_message_proto_rawDescGZIP(), []int{2}
}

func (x *ParsedAbiBlockMessage) GetChain() *Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetWitness() *Witness {
	if x != nil {
		return x.Witness
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetTransactions() []*ParsedAbiTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

var File_tron_parsed_abi_block_message_proto protoreflect.FileDescriptor

const file_tron_parsed_abi_block_message_proto_rawDesc = "" +
	"\n" +
	"#tron/parsed_abi_block_message.proto\x12\rtron_messages\x1a\x18tron/block_message.proto\x1a\"evm/parsed_abi_block_message.proto\"V\n" +
	"\fContractInfo\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\fR\aAddress\x12\x12\n" +
	"\x04Type\x18\x02 \x01(\tR\x04Type\x12\x18\n" +
	"\aTypeUrl\x18\x03 \x01(\tR\aTypeUrl\"\xfb\x03\n" +
	"\x14ParsedAbiTransaction\x12N\n" +
	"\x11TransactionHeader\x18\x01 \x01(\v2 .tron_messages.TransactionHeaderR\x11TransactionHeader\x120\n" +
	"\aReceipt\x18\x02 \x01(\v2\x16.tron_messages.ReceiptR\aReceipt\x12V\n" +
	"\x11TransactionStatus\x18\x03 \x01(\v2(.evm_messages.ParsedAbiTransactionStatusR\x11TransactionStatus\x12N\n" +
	"\x11TransactionResult\x18\x04 \x01(\v2 .tron_messages.TransactionResultR\x11TransactionResult\x12?\n" +
	"\fContractInfo\x18\x05 \x01(\v2\x1b.tron_messages.ContractInfoR\fContractInfo\x121\n" +
	"\x05Calls\x18\x06 \x03(\v2\x1b.evm_messages.ParsedAbiCallR\x05Calls\x12E\n" +
	"\x0eRewardWithdraw\x18\a \x01(\v2\x1d.tron_messages.RewardWithdrawR\x0eRewardWithdraw\"\xf2\x01\n" +
	"\x15ParsedAbiBlockMessage\x12*\n" +
	"\x05Chain\x18\x01 \x01(\v2\x14.tron_messages.ChainR\x05Chain\x122\n" +
	"\x06Header\x18\x02 \x01(\v2\x1a.tron_messages.BlockHeaderR\x06Header\x120\n" +
	"\aWitness\x18\x03 \x01(\v2\x16.tron_messages.WitnessR\aWitness\x12G\n" +
	"\fTransactions\x18\x04 \x03(\v2#.tron_messages.ParsedAbiTransactionR\fTransactionsb\x06proto3"

var (
	file_tron_parsed_abi_block_message_proto_rawDescOnce sync.Once
	file_tron_parsed_abi_block_message_proto_rawDescData []byte
)

func file_tron_parsed_abi_block_message_proto_rawDescGZIP() []byte {
	file_tron_parsed_abi_block_message_proto_rawDescOnce.Do(func() {
		file_tron_parsed_abi_block_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tron_parsed_abi_block_message_proto_rawDesc), len(file_tron_parsed_abi_block_message_proto_rawDesc)))
	})
	return file_tron_parsed_abi_block_message_proto_rawDescData
}

var file_tron_parsed_abi_block_message_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_tron_parsed_abi_block_message_proto_goTypes = []any{
	(*ContractInfo)(nil),                        // 0: tron_messages.ContractInfo
	(*ParsedAbiTransaction)(nil),                // 1: tron_messages.ParsedAbiTransaction
	(*ParsedAbiBlockMessage)(nil),               // 2: tron_messages.ParsedAbiBlockMessage
	(*TransactionHeader)(nil),                   // 3: tron_messages.TransactionHeader
	(*Receipt)(nil),                             // 4: tron_messages.Receipt
	(*messages.ParsedAbiTransactionStatus)(nil), // 5: evm_messages.ParsedAbiTransactionStatus
	(*TransactionResult)(nil),                   // 6: tron_messages.TransactionResult
	(*messages.ParsedAbiCall)(nil),              // 7: evm_messages.ParsedAbiCall
	(*RewardWithdraw)(nil),                      // 8: tron_messages.RewardWithdraw
	(*Chain)(nil),                               // 9: tron_messages.Chain
	(*BlockHeader)(nil),                         // 10: tron_messages.BlockHeader
	(*Witness)(nil),                             // 11: tron_messages.Witness
}
var file_tron_parsed_abi_block_message_proto_depIdxs = []int32{
	3,  // 0: tron_messages.ParsedAbiTransaction.TransactionHeader:type_name -> tron_messages.TransactionHeader
	4,  // 1: tron_messages.ParsedAbiTransaction.Receipt:type_name -> tron_messages.Receipt
	5,  // 2: tron_messages.ParsedAbiTransaction.TransactionStatus:type_name -> evm_messages.ParsedAbiTransactionStatus
	6,  // 3: tron_messages.ParsedAbiTransaction.TransactionResult:type_name -> tron_messages.TransactionResult
	0,  // 4: tron_messages.ParsedAbiTransaction.ContractInfo:type_name -> tron_messages.ContractInfo
	7,  // 5: tron_messages.ParsedAbiTransaction.Calls:type_name -> evm_messages.ParsedAbiCall
	8,  // 6: tron_messages.ParsedAbiTransaction.RewardWithdraw:type_name -> tron_messages.RewardWithdraw
	9,  // 7: tron_messages.ParsedAbiBlockMessage.Chain:type_name -> tron_messages.Chain
	10, // 8: tron_messages.ParsedAbiBlockMessage.Header:type_name -> tron_messages.BlockHeader
	11, // 9: tron_messages.ParsedAbiBlockMessage.Witness:type_name -> tron_messages.Witness
	1,  // 10: tron_messages.ParsedAbiBlockMessage.Transactions:type_name -> tron_messages.ParsedAbiTransaction
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_tron_parsed_abi_block_message_proto_init() }
func file_tron_parsed_abi_block_message_proto_init() {
	if File_tron_parsed_abi_block_message_proto != nil {
		return
	}
	file_tron_block_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tron_parsed_abi_block_message_proto_rawDesc), len(file_tron_parsed_abi_block_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_tron_parsed_abi_block_message_proto_goTypes,
		DependencyIndexes: file_tron_parsed_abi_block_message_proto_depIdxs,
		MessageInfos:      file_tron_parsed_abi_block_message_proto_msgTypes,
	}.Build()
	File_tron_parsed_abi_block_message_proto = out.File
	file_tron_parsed_abi_block_message_proto_goTypes = nil
	file_tron_parsed_abi_block_message_proto_depIdxs = nil
}
