# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market/trades.proto
# Protobuf Python Version: 6.33.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    0,
    '',
    'market/trades.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from market import marketdata_pb2 as market_dot_marketdata__pb2
from market import price_index_pb2 as market_dot_price__index__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13market/trades.proto\x12\x13marketdata_messages\x1a\x17market/marketdata.proto\x1a\x18market/price_index.proto\"D\n\x0bTransaction\x12\x0c\n\x04Hash\x18\x01 \x01(\t\x12\r\n\x05Index\x18\x02 \x01(\x05\x12\x0c\n\x04\x46rom\x18\x03 \x01(\t\x12\n\n\x02To\x18\x04 \x01(\t\"%\n\x05\x42lock\x12\x0e\n\x06Height\x18\x01 \x01(\x03\x12\x0c\n\x04Slot\x18\x02 \x01(\x03\"^\n\x04\x43\x61ll\x12\r\n\x05\x44\x65pth\x18\x01 \x01(\x05\x12\x10\n\x08\x43\x61llPath\x18\x02 \x01(\t\x12\x15\n\rSmartContract\x18\x03 \x01(\t\x12\x0e\n\x06Method\x18\x04 \x01(\t\x12\x0e\n\x06\x43\x61ller\x18\x05 \x01(\t\"\x19\n\x06Trader\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\t\"\x17\n\x04Pool\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\t\"\x80\x01\n\x05\x41sset\x12)\n\x05Token\x18\x01 \x01(\x0b\x32\x1a.marketdata_messages.Token\x12/\n\x08\x43urrency\x18\x02 \x01(\x0b\x32\x1d.marketdata_messages.Currency\x12\x0e\n\x06\x41mount\x18\x03 \x01(\x01\x12\x0b\n\x03Usd\x18\x04 \x01(\x01\"H\n\tTradeInfo\x12;\n\x0eTradeDirection\x18\x01 \x01(\x0e\x32#.marketdata_messages.TradeDirection\"\x9d\x03\n\x05Trade\x12+\n\x06Market\x18\x01 \x01(\x0b\x32\x1b.marketdata_messages.Market\x12\x35\n\x0bTransaction\x18\x02 \x01(\x0b\x32 .marketdata_messages.Transaction\x12)\n\x05\x42lock\x18\x03 \x01(\x0b\x32\x1a.marketdata_messages.Block\x12\'\n\x04\x43\x61ll\x18\x04 \x01(\x0b\x32\x19.marketdata_messages.Call\x12+\n\x06Trader\x18\x05 \x01(\x0b\x32\x1b.marketdata_messages.Trader\x12\'\n\x04Pool\x18\x06 \x01(\x0b\x32\x19.marketdata_messages.Pool\x12)\n\x05Quote\x18\x07 \x01(\x0b\x32\x1a.marketdata_messages.Asset\x12(\n\x04\x42\x61se\x18\x08 \x01(\x0b\x32\x1a.marketdata_messages.Asset\x12\x31\n\tTradeInfo\x18\t \x01(\x0b\x32\x1e.marketdata_messages.TradeInfo\"I\n\rTradesMessage\x12\x0c\n\x04Time\x18\x01 \x01(\x04\x12*\n\x06Trades\x18\x02 \x03(\x0b\x32\x1a.marketdata_messages.Trade*#\n\x0eTradeDirection\x12\x07\n\x03\x42uy\x10\x00\x12\x08\n\x04Sell\x10\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market.trades_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADEDIRECTION']._serialized_start=1048
  _globals['_TRADEDIRECTION']._serialized_end=1083
  _globals['_TRANSACTION']._serialized_start=95
  _globals['_TRANSACTION']._serialized_end=163
  _globals['_BLOCK']._serialized_start=165
  _globals['_BLOCK']._serialized_end=202
  _globals['_CALL']._serialized_start=204
  _globals['_CALL']._serialized_end=298
  _globals['_TRADER']._serialized_start=300
  _globals['_TRADER']._serialized_end=325
  _globals['_POOL']._serialized_start=327
  _globals['_POOL']._serialized_end=350
  _globals['_ASSET']._serialized_start=353
  _globals['_ASSET']._serialized_end=481
  _globals['_TRADEINFO']._serialized_start=483
  _globals['_TRADEINFO']._serialized_end=555
  _globals['_TRADE']._serialized_start=558
  _globals['_TRADE']._serialized_end=971
  _globals['_TRADESMESSAGE']._serialized_start=973
  _globals['_TRADESMESSAGE']._serialized_end=1046
# @@protoc_insertion_point(module_scope)
