// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: utxo/block_message.proto

package utxo_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BlockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockMessage) Reset() {
	*x = BlockMessage{}
	mi := &file_utxo_block_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockMessage) ProtoMessage() {}

func (x *BlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockMessage.ProtoReflect.Descriptor instead.
func (*BlockMessage) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{0}
}

func (x *BlockMessage) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BlockMessage) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type BlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Confirmations int64                  `protobuf:"varint,2,opt,name=Confirmations,proto3" json:"Confirmations,omitempty"`
	Size          int32                  `protobuf:"varint,3,opt,name=Size,proto3" json:"Size,omitempty"`
	StrippedSize  int32                  `protobuf:"varint,4,opt,name=StrippedSize,proto3" json:"StrippedSize,omitempty"`
	Weight        int32                  `protobuf:"varint,5,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Height        int64                  `protobuf:"varint,6,opt,name=Height,proto3" json:"Height,omitempty"`
	Version       int32                  `protobuf:"varint,7,opt,name=Version,proto3" json:"Version,omitempty"`
	VersionHex    []byte                 `protobuf:"bytes,8,opt,name=VersionHex,proto3" json:"VersionHex,omitempty"`
	MerkleRoot    []byte                 `protobuf:"bytes,9,opt,name=MerkleRoot,proto3" json:"MerkleRoot,omitempty"`
	Time          int64                  `protobuf:"varint,10,opt,name=Time,proto3" json:"Time,omitempty"`
	MedianTime    int64                  `protobuf:"varint,11,opt,name=MedianTime,proto3" json:"MedianTime,omitempty"`
	Nonce         uint32                 `protobuf:"varint,12,opt,name=Nonce,proto3" json:"Nonce,omitempty"`
	Bits          []byte                 `protobuf:"bytes,13,opt,name=Bits,proto3" json:"Bits,omitempty"`
	Difficulty    float64                `protobuf:"fixed64,14,opt,name=Difficulty,proto3" json:"Difficulty,omitempty"`
	Chainwork     []byte                 `protobuf:"bytes,15,opt,name=Chainwork,proto3" json:"Chainwork,omitempty"`
	NTx           uint32                 `protobuf:"varint,16,opt,name=NTx,proto3" json:"NTx,omitempty"`
	PreviousHash  []byte                 `protobuf:"bytes,17,opt,name=PreviousHash,proto3" json:"PreviousHash,omitempty"`
	NextHash      []byte                 `protobuf:"bytes,18,opt,name=NextHash,proto3" json:"NextHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlockHeader) Reset() {
	*x = BlockHeader{}
	mi := &file_utxo_block_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlockHeader) ProtoMessage() {}

func (x *BlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlockHeader.ProtoReflect.Descriptor instead.
func (*BlockHeader) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{1}
}

func (x *BlockHeader) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *BlockHeader) GetConfirmations() int64 {
	if x != nil {
		return x.Confirmations
	}
	return 0
}

func (x *BlockHeader) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BlockHeader) GetStrippedSize() int32 {
	if x != nil {
		return x.StrippedSize
	}
	return 0
}

func (x *BlockHeader) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BlockHeader) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BlockHeader) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *BlockHeader) GetVersionHex() []byte {
	if x != nil {
		return x.VersionHex
	}
	return nil
}

func (x *BlockHeader) GetMerkleRoot() []byte {
	if x != nil {
		return x.MerkleRoot
	}
	return nil
}

func (x *BlockHeader) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *BlockHeader) GetMedianTime() int64 {
	if x != nil {
		return x.MedianTime
	}
	return 0
}

func (x *BlockHeader) GetNonce() uint32 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *BlockHeader) GetBits() []byte {
	if x != nil {
		return x.Bits
	}
	return nil
}

func (x *BlockHeader) GetDifficulty() float64 {
	if x != nil {
		return x.Difficulty
	}
	return 0
}

func (x *BlockHeader) GetChainwork() []byte {
	if x != nil {
		return x.Chainwork
	}
	return nil
}

func (x *BlockHeader) GetNTx() uint32 {
	if x != nil {
		return x.NTx
	}
	return 0
}

func (x *BlockHeader) GetPreviousHash() []byte {
	if x != nil {
		return x.PreviousHash
	}
	return nil
}

func (x *BlockHeader) GetNextHash() []byte {
	if x != nil {
		return x.NextHash
	}
	return nil
}

type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *TransactionHeader     `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Inputs        []*TransactionInput    `protobuf:"bytes,2,rep,name=Inputs,proto3" json:"Inputs,omitempty"`
	Outputs       []*TransactionOutput   `protobuf:"bytes,3,rep,name=Outputs,proto3" json:"Outputs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_utxo_block_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{2}
}

func (x *Transaction) GetHeader() *TransactionHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Transaction) GetInputs() []*TransactionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *Transaction) GetOutputs() []*TransactionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

type TransactionHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           []byte                 `protobuf:"bytes,1,opt,name=Hex,proto3" json:"Hex,omitempty"`
	Id            []byte                 `protobuf:"bytes,2,opt,name=Id,proto3" json:"Id,omitempty"`
	Hash          []byte                 `protobuf:"bytes,3,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=Size,proto3" json:"Size,omitempty"`
	VSize         int32                  `protobuf:"varint,5,opt,name=VSize,proto3" json:"VSize,omitempty"`
	Weight        int32                  `protobuf:"varint,6,opt,name=Weight,proto3" json:"Weight,omitempty"`
	Version       uint32                 `protobuf:"varint,7,opt,name=Version,proto3" json:"Version,omitempty"`
	LockTime      uint32                 `protobuf:"varint,8,opt,name=LockTime,proto3" json:"LockTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionHeader) Reset() {
	*x = TransactionHeader{}
	mi := &file_utxo_block_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionHeader) ProtoMessage() {}

func (x *TransactionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionHeader.ProtoReflect.Descriptor instead.
func (*TransactionHeader) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{3}
}

func (x *TransactionHeader) GetHex() []byte {
	if x != nil {
		return x.Hex
	}
	return nil
}

func (x *TransactionHeader) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TransactionHeader) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *TransactionHeader) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TransactionHeader) GetVSize() int32 {
	if x != nil {
		return x.VSize
	}
	return 0
}

func (x *TransactionHeader) GetWeight() int32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *TransactionHeader) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *TransactionHeader) GetLockTime() uint32 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

type TransactionInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coinbase      []byte                 `protobuf:"bytes,1,opt,name=Coinbase,proto3" json:"Coinbase,omitempty"`
	TxId          []byte                 `protobuf:"bytes,2,opt,name=TxId,proto3" json:"TxId,omitempty"`
	VOut          uint32                 `protobuf:"varint,3,opt,name=VOut,proto3" json:"VOut,omitempty"`
	ScriptSig     *ScriptSig             `protobuf:"bytes,4,opt,name=ScriptSig,proto3" json:"ScriptSig,omitempty"`
	Sequence      uint32                 `protobuf:"varint,5,opt,name=Sequence,proto3" json:"Sequence,omitempty"`
	Witness       []string               `protobuf:"bytes,6,rep,name=Witness,proto3" json:"Witness,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionInput) Reset() {
	*x = TransactionInput{}
	mi := &file_utxo_block_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionInput) ProtoMessage() {}

func (x *TransactionInput) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionInput.ProtoReflect.Descriptor instead.
func (*TransactionInput) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{4}
}

func (x *TransactionInput) GetCoinbase() []byte {
	if x != nil {
		return x.Coinbase
	}
	return nil
}

func (x *TransactionInput) GetTxId() []byte {
	if x != nil {
		return x.TxId
	}
	return nil
}

func (x *TransactionInput) GetVOut() uint32 {
	if x != nil {
		return x.VOut
	}
	return 0
}

func (x *TransactionInput) GetScriptSig() *ScriptSig {
	if x != nil {
		return x.ScriptSig
	}
	return nil
}

func (x *TransactionInput) GetSequence() uint32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TransactionInput) GetWitness() []string {
	if x != nil {
		return x.Witness
	}
	return nil
}

type ScriptSig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asm           string                 `protobuf:"bytes,1,opt,name=Asm,proto3" json:"Asm,omitempty"`
	Hex           []byte                 `protobuf:"bytes,2,opt,name=Hex,proto3" json:"Hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptSig) Reset() {
	*x = ScriptSig{}
	mi := &file_utxo_block_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptSig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptSig) ProtoMessage() {}

func (x *ScriptSig) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptSig.ProtoReflect.Descriptor instead.
func (*ScriptSig) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{5}
}

func (x *ScriptSig) GetAsm() string {
	if x != nil {
		return x.Asm
	}
	return ""
}

func (x *ScriptSig) GetHex() []byte {
	if x != nil {
		return x.Hex
	}
	return nil
}

type TransactionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=Value,proto3" json:"Value,omitempty"`
	N             uint32                 `protobuf:"varint,2,opt,name=N,proto3" json:"N,omitempty"`
	ScriptPubKey  *ScriptPubKey          `protobuf:"bytes,3,opt,name=ScriptPubKey,proto3" json:"ScriptPubKey,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOutput) Reset() {
	*x = TransactionOutput{}
	mi := &file_utxo_block_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOutput) ProtoMessage() {}

func (x *TransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOutput.ProtoReflect.Descriptor instead.
func (*TransactionOutput) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{6}
}

func (x *TransactionOutput) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *TransactionOutput) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *TransactionOutput) GetScriptPubKey() *ScriptPubKey {
	if x != nil {
		return x.ScriptPubKey
	}
	return nil
}

type ScriptPubKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Asm           string                 `protobuf:"bytes,1,opt,name=Asm,proto3" json:"Asm,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=Desc,proto3" json:"Desc,omitempty"`
	Hex           []byte                 `protobuf:"bytes,3,opt,name=Hex,proto3" json:"Hex,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Address       string                 `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptPubKey) Reset() {
	*x = ScriptPubKey{}
	mi := &file_utxo_block_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptPubKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptPubKey) ProtoMessage() {}

func (x *ScriptPubKey) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptPubKey.ProtoReflect.Descriptor instead.
func (*ScriptPubKey) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{7}
}

func (x *ScriptPubKey) GetAsm() string {
	if x != nil {
		return x.Asm
	}
	return ""
}

func (x *ScriptPubKey) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

func (x *ScriptPubKey) GetHex() []byte {
	if x != nil {
		return x.Hex
	}
	return nil
}

func (x *ScriptPubKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ScriptPubKey) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type TransactionOutputWithBlockHash struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *TransactionOutput     `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	BlockHash     []byte                 `protobuf:"bytes,2,opt,name=BlockHash,proto3" json:"BlockHash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransactionOutputWithBlockHash) Reset() {
	*x = TransactionOutputWithBlockHash{}
	mi := &file_utxo_block_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionOutputWithBlockHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionOutputWithBlockHash) ProtoMessage() {}

func (x *TransactionOutputWithBlockHash) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_block_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionOutputWithBlockHash.ProtoReflect.Descriptor instead.
func (*TransactionOutputWithBlockHash) Descriptor() ([]byte, []int) {
	return file_utxo_block_message_proto_rawDescGZIP(), []int{8}
}

func (x *TransactionOutputWithBlockHash) GetOutput() *TransactionOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *TransactionOutputWithBlockHash) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

var File_utxo_block_message_proto protoreflect.FileDescriptor

const file_utxo_block_message_proto_rawDesc = "" +
	"\n" +
	"\x18utxo/block_message.proto\x12\rutxo_messages\"\x82\x01\n" +
	"\fBlockMessage\x122\n" +
	"\x06Header\x18\x01 \x01(\v2\x1a.utxo_messages.BlockHeaderR\x06Header\x12>\n" +
	"\fTransactions\x18\x02 \x03(\v2\x1a.utxo_messages.TransactionR\fTransactions\"\xf7\x03\n" +
	"\vBlockHeader\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\x12$\n" +
	"\rConfirmations\x18\x02 \x01(\x03R\rConfirmations\x12\x12\n" +
	"\x04Size\x18\x03 \x01(\x05R\x04Size\x12\"\n" +
	"\fStrippedSize\x18\x04 \x01(\x05R\fStrippedSize\x12\x16\n" +
	"\x06Weight\x18\x05 \x01(\x05R\x06Weight\x12\x16\n" +
	"\x06Height\x18\x06 \x01(\x03R\x06Height\x12\x18\n" +
	"\aVersion\x18\a \x01(\x05R\aVersion\x12\x1e\n" +
	"\n" +
	"VersionHex\x18\b \x01(\fR\n" +
	"VersionHex\x12\x1e\n" +
	"\n" +
	"MerkleRoot\x18\t \x01(\fR\n" +
	"MerkleRoot\x12\x12\n" +
	"\x04Time\x18\n" +
	" \x01(\x03R\x04Time\x12\x1e\n" +
	"\n" +
	"MedianTime\x18\v \x01(\x03R\n" +
	"MedianTime\x12\x14\n" +
	"\x05Nonce\x18\f \x01(\rR\x05Nonce\x12\x12\n" +
	"\x04Bits\x18\r \x01(\fR\x04Bits\x12\x1e\n" +
	"\n" +
	"Difficulty\x18\x0e \x01(\x01R\n" +
	"Difficulty\x12\x1c\n" +
	"\tChainwork\x18\x0f \x01(\fR\tChainwork\x12\x10\n" +
	"\x03NTx\x18\x10 \x01(\rR\x03NTx\x12\"\n" +
	"\fPreviousHash\x18\x11 \x01(\fR\fPreviousHash\x12\x1a\n" +
	"\bNextHash\x18\x12 \x01(\fR\bNextHash\"\xbc\x01\n" +
	"\vTransaction\x128\n" +
	"\x06Header\x18\x01 \x01(\v2 .utxo_messages.TransactionHeaderR\x06Header\x127\n" +
	"\x06Inputs\x18\x02 \x03(\v2\x1f.utxo_messages.TransactionInputR\x06Inputs\x12:\n" +
	"\aOutputs\x18\x03 \x03(\v2 .utxo_messages.TransactionOutputR\aOutputs\"\xc1\x01\n" +
	"\x11TransactionHeader\x12\x10\n" +
	"\x03Hex\x18\x01 \x01(\fR\x03Hex\x12\x0e\n" +
	"\x02Id\x18\x02 \x01(\fR\x02Id\x12\x12\n" +
	"\x04Hash\x18\x03 \x01(\fR\x04Hash\x12\x12\n" +
	"\x04Size\x18\x04 \x01(\x05R\x04Size\x12\x14\n" +
	"\x05VSize\x18\x05 \x01(\x05R\x05VSize\x12\x16\n" +
	"\x06Weight\x18\x06 \x01(\x05R\x06Weight\x12\x18\n" +
	"\aVersion\x18\a \x01(\rR\aVersion\x12\x1a\n" +
	"\bLockTime\x18\b \x01(\rR\bLockTime\"\xc4\x01\n" +
	"\x10TransactionInput\x12\x1a\n" +
	"\bCoinbase\x18\x01 \x01(\fR\bCoinbase\x12\x12\n" +
	"\x04TxId\x18\x02 \x01(\fR\x04TxId\x12\x12\n" +
	"\x04VOut\x18\x03 \x01(\rR\x04VOut\x126\n" +
	"\tScriptSig\x18\x04 \x01(\v2\x18.utxo_messages.ScriptSigR\tScriptSig\x12\x1a\n" +
	"\bSequence\x18\x05 \x01(\rR\bSequence\x12\x18\n" +
	"\aWitness\x18\x06 \x03(\tR\aWitness\"/\n" +
	"\tScriptSig\x12\x10\n" +
	"\x03Asm\x18\x01 \x01(\tR\x03Asm\x12\x10\n" +
	"\x03Hex\x18\x02 \x01(\fR\x03Hex\"x\n" +
	"\x11TransactionOutput\x12\x14\n" +
	"\x05Value\x18\x01 \x01(\x01R\x05Value\x12\f\n" +
	"\x01N\x18\x02 \x01(\rR\x01N\x12?\n" +
	"\fScriptPubKey\x18\x03 \x01(\v2\x1b.utxo_messages.ScriptPubKeyR\fScriptPubKey\"t\n" +
	"\fScriptPubKey\x12\x10\n" +
	"\x03Asm\x18\x01 \x01(\tR\x03Asm\x12\x12\n" +
	"\x04Desc\x18\x02 \x01(\tR\x04Desc\x12\x10\n" +
	"\x03Hex\x18\x03 \x01(\fR\x03Hex\x12\x12\n" +
	"\x04Type\x18\x04 \x01(\tR\x04Type\x12\x18\n" +
	"\aAddress\x18\x05 \x01(\tR\aAddress\"x\n" +
	"\x1eTransactionOutputWithBlockHash\x128\n" +
	"\x06Output\x18\x01 \x01(\v2 .utxo_messages.TransactionOutputR\x06Output\x12\x1c\n" +
	"\tBlockHash\x18\x02 \x01(\fR\tBlockHashb\x06proto3"

var (
	file_utxo_block_message_proto_rawDescOnce sync.Once
	file_utxo_block_message_proto_rawDescData []byte
)

func file_utxo_block_message_proto_rawDescGZIP() []byte {
	file_utxo_block_message_proto_rawDescOnce.Do(func() {
		file_utxo_block_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxo_block_message_proto_rawDesc), len(file_utxo_block_message_proto_rawDesc)))
	})
	return file_utxo_block_message_proto_rawDescData
}

var file_utxo_block_message_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_utxo_block_message_proto_goTypes = []any{
	(*BlockMessage)(nil),                   // 0: utxo_messages.BlockMessage
	(*BlockHeader)(nil),                    // 1: utxo_messages.BlockHeader
	(*Transaction)(nil),                    // 2: utxo_messages.Transaction
	(*TransactionHeader)(nil),              // 3: utxo_messages.TransactionHeader
	(*TransactionInput)(nil),               // 4: utxo_messages.TransactionInput
	(*ScriptSig)(nil),                      // 5: utxo_messages.ScriptSig
	(*TransactionOutput)(nil),              // 6: utxo_messages.TransactionOutput
	(*ScriptPubKey)(nil),                   // 7: utxo_messages.ScriptPubKey
	(*TransactionOutputWithBlockHash)(nil), // 8: utxo_messages.TransactionOutputWithBlockHash
}
var file_utxo_block_message_proto_depIdxs = []int32{
	1, // 0: utxo_messages.BlockMessage.Header:type_name -> utxo_messages.BlockHeader
	2, // 1: utxo_messages.BlockMessage.Transactions:type_name -> utxo_messages.Transaction
	3, // 2: utxo_messages.Transaction.Header:type_name -> utxo_messages.TransactionHeader
	4, // 3: utxo_messages.Transaction.Inputs:type_name -> utxo_messages.TransactionInput
	6, // 4: utxo_messages.Transaction.Outputs:type_name -> utxo_messages.TransactionOutput
	5, // 5: utxo_messages.TransactionInput.ScriptSig:type_name -> utxo_messages.ScriptSig
	7, // 6: utxo_messages.TransactionOutput.ScriptPubKey:type_name -> utxo_messages.ScriptPubKey
	6, // 7: utxo_messages.TransactionOutputWithBlockHash.Output:type_name -> utxo_messages.TransactionOutput
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_utxo_block_message_proto_init() }
func file_utxo_block_message_proto_init() {
	if File_utxo_block_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxo_block_message_proto_rawDesc), len(file_utxo_block_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utxo_block_message_proto_goTypes,
		DependencyIndexes: file_utxo_block_message_proto_depIdxs,
		MessageInfos:      file_utxo_block_message_proto_msgTypes,
	}.Build()
	File_utxo_block_message_proto = out.File
	file_utxo_block_message_proto_goTypes = nil
	file_utxo_block_message_proto_depIdxs = nil
}
