// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.0
// source: utxo/parsed_block_message.proto

package utxo_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ScriptType int32

const (
	ScriptType_UNKNOWN               ScriptType = 0
	ScriptType_PUBKEY                ScriptType = 1
	ScriptType_PUBKEYHASH            ScriptType = 2
	ScriptType_SCRIPTHASH            ScriptType = 3
	ScriptType_MULTISIG              ScriptType = 4
	ScriptType_NULLDATA              ScriptType = 5
	ScriptType_WITNESS_V0_KEYHASH    ScriptType = 6
	ScriptType_WITNESS_V0_SCRIPTHASH ScriptType = 7
	ScriptType_WITNESS_UNKNOWN       ScriptType = 8
)

// Enum value maps for ScriptType.
var (
	ScriptType_name = map[int32]string{
		0: "UNKNOWN",
		1: "PUBKEY",
		2: "PUBKEYHASH",
		3: "SCRIPTHASH",
		4: "MULTISIG",
		5: "NULLDATA",
		6: "WITNESS_V0_KEYHASH",
		7: "WITNESS_V0_SCRIPTHASH",
		8: "WITNESS_UNKNOWN",
	}
	ScriptType_value = map[string]int32{
		"UNKNOWN":               0,
		"PUBKEY":                1,
		"PUBKEYHASH":            2,
		"SCRIPTHASH":            3,
		"MULTISIG":              4,
		"NULLDATA":              5,
		"WITNESS_V0_KEYHASH":    6,
		"WITNESS_V0_SCRIPTHASH": 7,
		"WITNESS_UNKNOWN":       8,
	}
)

func (x ScriptType) Enum() *ScriptType {
	p := new(ScriptType)
	*p = x
	return p
}

func (x ScriptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ScriptType) Descriptor() protoreflect.EnumDescriptor {
	return file_utxo_parsed_block_message_proto_enumTypes[0].Descriptor()
}

func (ScriptType) Type() protoreflect.EnumType {
	return &file_utxo_parsed_block_message_proto_enumTypes[0]
}

func (x ScriptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ScriptType.Descriptor instead.
func (ScriptType) EnumDescriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{0}
}

type ParsedBlockMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *BlockHeader           `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Transactions  []*ParsedTransaction   `protobuf:"bytes,2,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedBlockMessage) Reset() {
	*x = ParsedBlockMessage{}
	mi := &file_utxo_parsed_block_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedBlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedBlockMessage) ProtoMessage() {}

func (x *ParsedBlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_parsed_block_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedBlockMessage.ProtoReflect.Descriptor instead.
func (*ParsedBlockMessage) Descriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{0}
}

func (x *ParsedBlockMessage) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedBlockMessage) GetTransactions() []*ParsedTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type ParsedTransaction struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Header        *TransactionHeader         `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Inputs        []*ParsedTransactionInput  `protobuf:"bytes,2,rep,name=Inputs,proto3" json:"Inputs,omitempty"`
	Outputs       []*ParsedTransactionOutput `protobuf:"bytes,3,rep,name=Outputs,proto3" json:"Outputs,omitempty"`
	Fee           uint64                     `protobuf:"varint,4,opt,name=Fee,proto3" json:"Fee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedTransaction) Reset() {
	*x = ParsedTransaction{}
	mi := &file_utxo_parsed_block_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTransaction) ProtoMessage() {}

func (x *ParsedTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_parsed_block_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTransaction.ProtoReflect.Descriptor instead.
func (*ParsedTransaction) Descriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{1}
}

func (x *ParsedTransaction) GetHeader() *TransactionHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedTransaction) GetInputs() []*ParsedTransactionInput {
	if x != nil {
		return x.Inputs
	}
	return nil
}

func (x *ParsedTransaction) GetOutputs() []*ParsedTransactionOutput {
	if x != nil {
		return x.Outputs
	}
	return nil
}

func (x *ParsedTransaction) GetFee() uint64 {
	if x != nil {
		return x.Fee
	}
	return 0
}

type ParsedTransactionInput struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Input         *TransactionInput        `protobuf:"bytes,2,opt,name=Input,proto3" json:"Input,omitempty"`
	SpentOutput   *ParsedTransactionOutput `protobuf:"bytes,3,opt,name=SpentOutput,proto3" json:"SpentOutput,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedTransactionInput) Reset() {
	*x = ParsedTransactionInput{}
	mi := &file_utxo_parsed_block_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedTransactionInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTransactionInput) ProtoMessage() {}

func (x *ParsedTransactionInput) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_parsed_block_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTransactionInput.ProtoReflect.Descriptor instead.
func (*ParsedTransactionInput) Descriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{2}
}

func (x *ParsedTransactionInput) GetInput() *TransactionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ParsedTransactionInput) GetSpentOutput() *ParsedTransactionOutput {
	if x != nil {
		return x.SpentOutput
	}
	return nil
}

type MinBlockHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hash          []byte                 `protobuf:"bytes,1,opt,name=Hash,proto3" json:"Hash,omitempty"`
	Height        int64                  `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	Time          int64                  `protobuf:"varint,3,opt,name=Time,proto3" json:"Time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinBlockHeader) Reset() {
	*x = MinBlockHeader{}
	mi := &file_utxo_parsed_block_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinBlockHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinBlockHeader) ProtoMessage() {}

func (x *MinBlockHeader) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_parsed_block_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinBlockHeader.ProtoReflect.Descriptor instead.
func (*MinBlockHeader) Descriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{3}
}

func (x *MinBlockHeader) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

func (x *MinBlockHeader) GetHeight() int64 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MinBlockHeader) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

type ParsedTransactionOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        *TransactionOutput     `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=Address,proto3" json:"Address,omitempty"`
	ScriptType    ScriptType             `protobuf:"varint,3,opt,name=ScriptType,proto3,enum=utxo_messages.ScriptType" json:"ScriptType,omitempty"`
	Script        []byte                 `protobuf:"bytes,4,opt,name=Script,proto3" json:"Script,omitempty"`
	ReqSigs       uint32                 `protobuf:"varint,5,opt,name=ReqSigs,proto3" json:"ReqSigs,omitempty"`
	Value         uint64                 `protobuf:"varint,6,opt,name=Value,proto3" json:"Value,omitempty"`
	Block         *MinBlockHeader        `protobuf:"bytes,7,opt,name=Block,proto3" json:"Block,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedTransactionOutput) Reset() {
	*x = ParsedTransactionOutput{}
	mi := &file_utxo_parsed_block_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedTransactionOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedTransactionOutput) ProtoMessage() {}

func (x *ParsedTransactionOutput) ProtoReflect() protoreflect.Message {
	mi := &file_utxo_parsed_block_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedTransactionOutput.ProtoReflect.Descriptor instead.
func (*ParsedTransactionOutput) Descriptor() ([]byte, []int) {
	return file_utxo_parsed_block_message_proto_rawDescGZIP(), []int{4}
}

func (x *ParsedTransactionOutput) GetOutput() *TransactionOutput {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ParsedTransactionOutput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *ParsedTransactionOutput) GetScriptType() ScriptType {
	if x != nil {
		return x.ScriptType
	}
	return ScriptType_UNKNOWN
}

func (x *ParsedTransactionOutput) GetScript() []byte {
	if x != nil {
		return x.Script
	}
	return nil
}

func (x *ParsedTransactionOutput) GetReqSigs() uint32 {
	if x != nil {
		return x.ReqSigs
	}
	return 0
}

func (x *ParsedTransactionOutput) GetValue() uint64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *ParsedTransactionOutput) GetBlock() *MinBlockHeader {
	if x != nil {
		return x.Block
	}
	return nil
}

var File_utxo_parsed_block_message_proto protoreflect.FileDescriptor

const file_utxo_parsed_block_message_proto_rawDesc = "" +
	"\n" +
	"\x1futxo/parsed_block_message.proto\x12\rutxo_messages\x1a\x18utxo/block_message.proto\"\x8e\x01\n" +
	"\x12ParsedBlockMessage\x122\n" +
	"\x06Header\x18\x01 \x01(\v2\x1a.utxo_messages.BlockHeaderR\x06Header\x12D\n" +
	"\fTransactions\x18\x02 \x03(\v2 .utxo_messages.ParsedTransactionR\fTransactions\"\xe0\x01\n" +
	"\x11ParsedTransaction\x128\n" +
	"\x06Header\x18\x01 \x01(\v2 .utxo_messages.TransactionHeaderR\x06Header\x12=\n" +
	"\x06Inputs\x18\x02 \x03(\v2%.utxo_messages.ParsedTransactionInputR\x06Inputs\x12@\n" +
	"\aOutputs\x18\x03 \x03(\v2&.utxo_messages.ParsedTransactionOutputR\aOutputs\x12\x10\n" +
	"\x03Fee\x18\x04 \x01(\x04R\x03Fee\"\x99\x01\n" +
	"\x16ParsedTransactionInput\x125\n" +
	"\x05Input\x18\x02 \x01(\v2\x1f.utxo_messages.TransactionInputR\x05Input\x12H\n" +
	"\vSpentOutput\x18\x03 \x01(\v2&.utxo_messages.ParsedTransactionOutputR\vSpentOutput\"P\n" +
	"\x0eMinBlockHeader\x12\x12\n" +
	"\x04Hash\x18\x01 \x01(\fR\x04Hash\x12\x16\n" +
	"\x06Height\x18\x02 \x01(\x03R\x06Height\x12\x12\n" +
	"\x04Time\x18\x03 \x01(\x03R\x04Time\"\xa5\x02\n" +
	"\x17ParsedTransactionOutput\x128\n" +
	"\x06Output\x18\x01 \x01(\v2 .utxo_messages.TransactionOutputR\x06Output\x12\x18\n" +
	"\aAddress\x18\x02 \x01(\tR\aAddress\x129\n" +
	"\n" +
	"ScriptType\x18\x03 \x01(\x0e2\x19.utxo_messages.ScriptTypeR\n" +
	"ScriptType\x12\x16\n" +
	"\x06Script\x18\x04 \x01(\fR\x06Script\x12\x18\n" +
	"\aReqSigs\x18\x05 \x01(\rR\aReqSigs\x12\x14\n" +
	"\x05Value\x18\x06 \x01(\x04R\x05Value\x123\n" +
	"\x05Block\x18\a \x01(\v2\x1d.utxo_messages.MinBlockHeaderR\x05Block*\xa9\x01\n" +
	"\n" +
	"ScriptType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06PUBKEY\x10\x01\x12\x0e\n" +
	"\n" +
	"PUBKEYHASH\x10\x02\x12\x0e\n" +
	"\n" +
	"SCRIPTHASH\x10\x03\x12\f\n" +
	"\bMULTISIG\x10\x04\x12\f\n" +
	"\bNULLDATA\x10\x05\x12\x16\n" +
	"\x12WITNESS_V0_KEYHASH\x10\x06\x12\x19\n" +
	"\x15WITNESS_V0_SCRIPTHASH\x10\a\x12\x13\n" +
	"\x0fWITNESS_UNKNOWN\x10\bb\x06proto3"

var (
	file_utxo_parsed_block_message_proto_rawDescOnce sync.Once
	file_utxo_parsed_block_message_proto_rawDescData []byte
)

func file_utxo_parsed_block_message_proto_rawDescGZIP() []byte {
	file_utxo_parsed_block_message_proto_rawDescOnce.Do(func() {
		file_utxo_parsed_block_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_utxo_parsed_block_message_proto_rawDesc), len(file_utxo_parsed_block_message_proto_rawDesc)))
	})
	return file_utxo_parsed_block_message_proto_rawDescData
}

var file_utxo_parsed_block_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_utxo_parsed_block_message_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_utxo_parsed_block_message_proto_goTypes = []any{
	(ScriptType)(0),                 // 0: utxo_messages.ScriptType
	(*ParsedBlockMessage)(nil),      // 1: utxo_messages.ParsedBlockMessage
	(*ParsedTransaction)(nil),       // 2: utxo_messages.ParsedTransaction
	(*ParsedTransactionInput)(nil),  // 3: utxo_messages.ParsedTransactionInput
	(*MinBlockHeader)(nil),          // 4: utxo_messages.MinBlockHeader
	(*ParsedTransactionOutput)(nil), // 5: utxo_messages.ParsedTransactionOutput
	(*BlockHeader)(nil),             // 6: utxo_messages.BlockHeader
	(*TransactionHeader)(nil),       // 7: utxo_messages.TransactionHeader
	(*TransactionInput)(nil),        // 8: utxo_messages.TransactionInput
	(*TransactionOutput)(nil),       // 9: utxo_messages.TransactionOutput
}
var file_utxo_parsed_block_message_proto_depIdxs = []int32{
	6,  // 0: utxo_messages.ParsedBlockMessage.Header:type_name -> utxo_messages.BlockHeader
	2,  // 1: utxo_messages.ParsedBlockMessage.Transactions:type_name -> utxo_messages.ParsedTransaction
	7,  // 2: utxo_messages.ParsedTransaction.Header:type_name -> utxo_messages.TransactionHeader
	3,  // 3: utxo_messages.ParsedTransaction.Inputs:type_name -> utxo_messages.ParsedTransactionInput
	5,  // 4: utxo_messages.ParsedTransaction.Outputs:type_name -> utxo_messages.ParsedTransactionOutput
	8,  // 5: utxo_messages.ParsedTransactionInput.Input:type_name -> utxo_messages.TransactionInput
	5,  // 6: utxo_messages.ParsedTransactionInput.SpentOutput:type_name -> utxo_messages.ParsedTransactionOutput
	9,  // 7: utxo_messages.ParsedTransactionOutput.Output:type_name -> utxo_messages.TransactionOutput
	0,  // 8: utxo_messages.ParsedTransactionOutput.ScriptType:type_name -> utxo_messages.ScriptType
	4,  // 9: utxo_messages.ParsedTransactionOutput.Block:type_name -> utxo_messages.MinBlockHeader
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_utxo_parsed_block_message_proto_init() }
func file_utxo_parsed_block_message_proto_init() {
	if File_utxo_parsed_block_message_proto != nil {
		return
	}
	file_utxo_block_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_utxo_parsed_block_message_proto_rawDesc), len(file_utxo_parsed_block_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_utxo_parsed_block_message_proto_goTypes,
		DependencyIndexes: file_utxo_parsed_block_message_proto_depIdxs,
		EnumInfos:         file_utxo_parsed_block_message_proto_enumTypes,
		MessageInfos:      file_utxo_parsed_block_message_proto_msgTypes,
	}.Build()
	File_utxo_parsed_block_message_proto = out.File
	file_utxo_parsed_block_message_proto_goTypes = nil
	file_utxo_parsed_block_message_proto_depIdxs = nil
}
