// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.32.0
// source: market/pool.proto

package marketdata_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
	Id            *string                `protobuf:"bytes,2,opt,name=Id,proto3,oneof" json:"Id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_market_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_market_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_market_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Pool) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Pool) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

var File_market_pool_proto protoreflect.FileDescriptor

const file_market_pool_proto_rawDesc = "" +
	"\n" +
	"\x11market/pool.proto\x12\x13marketdata_messages\"<\n" +
	"\x04Pool\x12\x18\n" +
	"\aAddress\x18\x01 \x01(\tR\aAddress\x12\x13\n" +
	"\x02Id\x18\x02 \x01(\tH\x00R\x02Id\x88\x01\x01B\x05\n" +
	"\x03_Idb\x06proto3"

var (
	file_market_pool_proto_rawDescOnce sync.Once
	file_market_pool_proto_rawDescData []byte
)

func file_market_pool_proto_rawDescGZIP() []byte {
	file_market_pool_proto_rawDescOnce.Do(func() {
		file_market_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_pool_proto_rawDesc), len(file_market_pool_proto_rawDesc)))
	})
	return file_market_pool_proto_rawDescData
}

var file_market_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_market_pool_proto_goTypes = []any{
	(*Pool)(nil), // 0: marketdata_messages.Pool
}
var file_market_pool_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_market_pool_proto_init() }
func file_market_pool_proto_init() {
	if File_market_pool_proto != nil {
		return
	}
	file_market_pool_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_pool_proto_rawDesc), len(file_market_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_pool_proto_goTypes,
		DependencyIndexes: file_market_pool_proto_depIdxs,
		MessageInfos:      file_market_pool_proto_msgTypes,
	}.Build()
	File_market_pool_proto = out.File
	file_market_pool_proto_goTypes = nil
	file_market_pool_proto_depIdxs = nil
}
