// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: market/price_index.proto

package marketdata_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Symbol        string                 `protobuf:"bytes,3,opt,name=Symbol,proto3" json:"Symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_market_price_index_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type Market struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Network        string                 `protobuf:"bytes,2,opt,name=Network,proto3" json:"Network,omitempty"` // LowCardinality string in clickhouse
	NetworkBid     string                 `protobuf:"bytes,3,opt,name=NetworkBid,proto3" json:"NetworkBid,omitempty"`
	Name           string                 `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	Address        string                 `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Protocol       string                 `protobuf:"bytes,6,opt,name=Protocol,proto3" json:"Protocol,omitempty"`             // LowCardinality string in clickhouse
	ProtocolFamily string                 `protobuf:"bytes,7,opt,name=ProtocolFamily,proto3" json:"ProtocolFamily,omitempty"` // LowCardinality string in clickhouse
	Program        string                 `protobuf:"bytes,8,opt,name=Program,proto3" json:"Program,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Market) Reset() {
	*x = Market{}
	mi := &file_market_price_index_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Market) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Market) ProtoMessage() {}

func (x *Market) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Market.ProtoReflect.Descriptor instead.
func (*Market) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{1}
}

func (x *Market) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Market) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Market) GetNetworkBid() string {
	if x != nil {
		return x.NetworkBid
	}
	return ""
}

func (x *Market) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Market) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Market) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Market) GetProtocolFamily() string {
	if x != nil {
		return x.ProtocolFamily
	}
	return ""
}

func (x *Market) GetProgram() string {
	if x != nil {
		return x.Program
	}
	return ""
}

type Amounts struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Base                float32                `protobuf:"fixed32,1,opt,name=Base,proto3" json:"Base,omitempty"`
	Quote               float32                `protobuf:"fixed32,2,opt,name=Quote,proto3" json:"Quote,omitempty"`
	Usd                 float32                `protobuf:"fixed32,3,opt,name=Usd,proto3" json:"Usd,omitempty"`
	BaseAttributedToUsd float32                `protobuf:"fixed32,4,opt,name=BaseAttributedToUsd,proto3" json:"BaseAttributedToUsd,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *Amounts) Reset() {
	*x = Amounts{}
	mi := &file_market_price_index_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Amounts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Amounts) ProtoMessage() {}

func (x *Amounts) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Amounts.ProtoReflect.Descriptor instead.
func (*Amounts) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{2}
}

func (x *Amounts) GetBase() float32 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *Amounts) GetQuote() float32 {
	if x != nil {
		return x.Quote
	}
	return 0
}

func (x *Amounts) GetUsd() float32 {
	if x != nil {
		return x.Usd
	}
	return 0
}

func (x *Amounts) GetBaseAttributedToUsd() float32 {
	if x != nil {
		return x.BaseAttributedToUsd
	}
	return 0
}

type Quote struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QuoteCurrency *Currency              `protobuf:"bytes,1,opt,name=QuoteCurrency,proto3" json:"QuoteCurrency,omitempty"`
	Amounts       *Amounts               `protobuf:"bytes,2,opt,name=Amounts,proto3" json:"Amounts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Quote) Reset() {
	*x = Quote{}
	mi := &file_market_price_index_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{3}
}

func (x *Quote) GetQuoteCurrency() *Currency {
	if x != nil {
		return x.QuoteCurrency
	}
	return nil
}

func (x *Quote) GetAmounts() *Amounts {
	if x != nil {
		return x.Amounts
	}
	return nil
}

type TimeInterval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      uint32                 `protobuf:"varint,1,opt,name=Duration,proto3" json:"Duration,omitempty"`
	Start         uint32                 `protobuf:"varint,2,opt,name=Start,proto3" json:"Start,omitempty"`
	End           uint32                 `protobuf:"varint,3,opt,name=End,proto3" json:"End,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeInterval) Reset() {
	*x = TimeInterval{}
	mi := &file_market_price_index_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeInterval) ProtoMessage() {}

func (x *TimeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeInterval.ProtoReflect.Descriptor instead.
func (*TimeInterval) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{4}
}

func (x *TimeInterval) GetDuration() uint32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *TimeInterval) GetStart() uint32 {
	if x != nil {
		return x.Start
	}
	return 0
}

func (x *TimeInterval) GetEnd() uint32 {
	if x != nil {
		return x.End
	}
	return 0
}

type Ohlc struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Open          float32                `protobuf:"fixed32,1,opt,name=Open,proto3" json:"Open,omitempty"`
	Close         float32                `protobuf:"fixed32,2,opt,name=Close,proto3" json:"Close,omitempty"`
	High          float32                `protobuf:"fixed32,3,opt,name=High,proto3" json:"High,omitempty"`
	Low           float32                `protobuf:"fixed32,4,opt,name=Low,proto3" json:"Low,omitempty"`
	Volume        float32                `protobuf:"fixed32,5,opt,name=Volume,proto3" json:"Volume,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ohlc) Reset() {
	*x = Ohlc{}
	mi := &file_market_price_index_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ohlc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ohlc) ProtoMessage() {}

func (x *Ohlc) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ohlc.ProtoReflect.Descriptor instead.
func (*Ohlc) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{5}
}

func (x *Ohlc) GetOpen() float32 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *Ohlc) GetClose() float32 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *Ohlc) GetHigh() float32 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *Ohlc) GetLow() float32 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *Ohlc) GetVolume() float32 {
	if x != nil {
		return x.Volume
	}
	return 0
}

type PriceByTimeInterval struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	TimeInterval                *TimeInterval          `protobuf:"bytes,1,opt,name=TimeInterval,proto3" json:"TimeInterval,omitempty"`
	Amounts                     *Amounts               `protobuf:"bytes,2,opt,name=Amounts,proto3" json:"Amounts,omitempty"`
	MeanPrice                   float32                `protobuf:"fixed32,3,opt,name=MeanPrice,proto3" json:"MeanPrice,omitempty"`
	SimpleMovingAverage         float32                `protobuf:"fixed32,4,opt,name=SimpleMovingAverage,proto3" json:"SimpleMovingAverage,omitempty"`
	WeightedSimpleMovingAverage float32                `protobuf:"fixed32,5,opt,name=WeightedSimpleMovingAverage,proto3" json:"WeightedSimpleMovingAverage,omitempty"`
	ExponentialMovingAverage    float32                `protobuf:"fixed32,6,opt,name=ExponentialMovingAverage,proto3" json:"ExponentialMovingAverage,omitempty"`
	Ohlc                        *Ohlc                  `protobuf:"bytes,7,opt,name=Ohlc,proto3" json:"Ohlc,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *PriceByTimeInterval) Reset() {
	*x = PriceByTimeInterval{}
	mi := &file_market_price_index_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceByTimeInterval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceByTimeInterval) ProtoMessage() {}

func (x *PriceByTimeInterval) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceByTimeInterval.ProtoReflect.Descriptor instead.
func (*PriceByTimeInterval) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{6}
}

func (x *PriceByTimeInterval) GetTimeInterval() *TimeInterval {
	if x != nil {
		return x.TimeInterval
	}
	return nil
}

func (x *PriceByTimeInterval) GetAmounts() *Amounts {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *PriceByTimeInterval) GetMeanPrice() float32 {
	if x != nil {
		return x.MeanPrice
	}
	return 0
}

func (x *PriceByTimeInterval) GetSimpleMovingAverage() float32 {
	if x != nil {
		return x.SimpleMovingAverage
	}
	return 0
}

func (x *PriceByTimeInterval) GetWeightedSimpleMovingAverage() float32 {
	if x != nil {
		return x.WeightedSimpleMovingAverage
	}
	return 0
}

func (x *PriceByTimeInterval) GetExponentialMovingAverage() float32 {
	if x != nil {
		return x.ExponentialMovingAverage
	}
	return 0
}

func (x *PriceByTimeInterval) GetOhlc() *Ohlc {
	if x != nil {
		return x.Ohlc
	}
	return nil
}

type PriceByVolume struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetVolume  float32                `protobuf:"fixed32,1,opt,name=TargetVolume,proto3" json:"TargetVolume,omitempty"`
	TimeInterval  *TimeInterval          `protobuf:"bytes,2,opt,name=TimeInterval,proto3" json:"TimeInterval,omitempty"`
	Amounts       *Amounts               `protobuf:"bytes,3,opt,name=Amounts,proto3" json:"Amounts,omitempty"`
	MeanPrice     float32                `protobuf:"fixed32,4,opt,name=MeanPrice,proto3" json:"MeanPrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceByVolume) Reset() {
	*x = PriceByVolume{}
	mi := &file_market_price_index_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceByVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceByVolume) ProtoMessage() {}

func (x *PriceByVolume) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceByVolume.ProtoReflect.Descriptor instead.
func (*PriceByVolume) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{7}
}

func (x *PriceByVolume) GetTargetVolume() float32 {
	if x != nil {
		return x.TargetVolume
	}
	return 0
}

func (x *PriceByVolume) GetTimeInterval() *TimeInterval {
	if x != nil {
		return x.TimeInterval
	}
	return nil
}

func (x *PriceByVolume) GetAmounts() *Amounts {
	if x != nil {
		return x.Amounts
	}
	return nil
}

func (x *PriceByVolume) GetMeanPrice() float32 {
	if x != nil {
		return x.MeanPrice
	}
	return 0
}

type EstimatedPrices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdaptivePrice float32                `protobuf:"fixed32,1,opt,name=AdaptivePrice,proto3" json:"AdaptivePrice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EstimatedPrices) Reset() {
	*x = EstimatedPrices{}
	mi := &file_market_price_index_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EstimatedPrices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EstimatedPrices) ProtoMessage() {}

func (x *EstimatedPrices) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EstimatedPrices.ProtoReflect.Descriptor instead.
func (*EstimatedPrices) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{8}
}

func (x *EstimatedPrices) GetAdaptivePrice() float32 {
	if x != nil {
		return x.AdaptivePrice
	}
	return 0
}

type PriceUpdate struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Quotes               []*Quote               `protobuf:"bytes,1,rep,name=Quotes,proto3" json:"Quotes,omitempty"`
	PriceByTimeIntervals []*PriceByTimeInterval `protobuf:"bytes,2,rep,name=PriceByTimeIntervals,proto3" json:"PriceByTimeIntervals,omitempty"`
	PriceByVolumes       []*PriceByVolume       `protobuf:"bytes,3,rep,name=PriceByVolumes,proto3" json:"PriceByVolumes,omitempty"`
	Estimates            *EstimatedPrices       `protobuf:"bytes,4,opt,name=Estimates,proto3" json:"Estimates,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PriceUpdate) Reset() {
	*x = PriceUpdate{}
	mi := &file_market_price_index_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceUpdate) ProtoMessage() {}

func (x *PriceUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceUpdate.ProtoReflect.Descriptor instead.
func (*PriceUpdate) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{9}
}

func (x *PriceUpdate) GetQuotes() []*Quote {
	if x != nil {
		return x.Quotes
	}
	return nil
}

func (x *PriceUpdate) GetPriceByTimeIntervals() []*PriceByTimeInterval {
	if x != nil {
		return x.PriceByTimeIntervals
	}
	return nil
}

func (x *PriceUpdate) GetPriceByVolumes() []*PriceByVolume {
	if x != nil {
		return x.PriceByVolumes
	}
	return nil
}

func (x *PriceUpdate) GetEstimates() *EstimatedPrices {
	if x != nil {
		return x.Estimates
	}
	return nil
}

type MarketCapUpdate struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	TotalSupply              float64                `protobuf:"fixed64,1,opt,name=TotalSupply,proto3" json:"TotalSupply,omitempty"`
	MarketCap                float64                `protobuf:"fixed64,2,opt,name=MarketCap,proto3" json:"MarketCap,omitempty"`
	FullyDilutedValuationUsd float64                `protobuf:"fixed64,3,opt,name=FullyDilutedValuationUsd,proto3" json:"FullyDilutedValuationUsd,omitempty"` // Fully diluted valuation (FDV) is a market cap if the max supply was in circulation
	CirculatingSupply        *float64               `protobuf:"fixed64,4,opt,name=CirculatingSupply,proto3,oneof" json:"CirculatingSupply,omitempty"`
	MaxSupply                *float64               `protobuf:"fixed64,5,opt,name=MaxSupply,proto3,oneof" json:"MaxSupply,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *MarketCapUpdate) Reset() {
	*x = MarketCapUpdate{}
	mi := &file_market_price_index_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketCapUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketCapUpdate) ProtoMessage() {}

func (x *MarketCapUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketCapUpdate.ProtoReflect.Descriptor instead.
func (*MarketCapUpdate) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{10}
}

func (x *MarketCapUpdate) GetTotalSupply() float64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *MarketCapUpdate) GetMarketCap() float64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *MarketCapUpdate) GetFullyDilutedValuationUsd() float64 {
	if x != nil {
		return x.FullyDilutedValuationUsd
	}
	return 0
}

func (x *MarketCapUpdate) GetCirculatingSupply() float64 {
	if x != nil && x.CirculatingSupply != nil {
		return *x.CirculatingSupply
	}
	return 0
}

func (x *MarketCapUpdate) GetMaxSupply() float64 {
	if x != nil && x.MaxSupply != nil {
		return *x.MaxSupply
	}
	return 0
}

type CurrencyUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Currency        *Currency              `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	PriceUpdate     *PriceUpdate           `protobuf:"bytes,2,opt,name=PriceUpdate,proto3" json:"PriceUpdate,omitempty"`
	MarketCapUpdate *MarketCapUpdate       `protobuf:"bytes,3,opt,name=MarketCapUpdate,proto3,oneof" json:"MarketCapUpdate,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CurrencyUpdate) Reset() {
	*x = CurrencyUpdate{}
	mi := &file_market_price_index_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyUpdate) ProtoMessage() {}

func (x *CurrencyUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyUpdate.ProtoReflect.Descriptor instead.
func (*CurrencyUpdate) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{11}
}

func (x *CurrencyUpdate) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *CurrencyUpdate) GetPriceUpdate() *PriceUpdate {
	if x != nil {
		return x.PriceUpdate
	}
	return nil
}

func (x *CurrencyUpdate) GetMarketCapUpdate() *MarketCapUpdate {
	if x != nil {
		return x.MarketCapUpdate
	}
	return nil
}

type TokenUpdate struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Currency        *Currency              `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	Token           *Token                 `protobuf:"bytes,2,opt,name=Token,proto3" json:"Token,omitempty"`
	PriceUpdate     *PriceUpdate           `protobuf:"bytes,3,opt,name=PriceUpdate,proto3" json:"PriceUpdate,omitempty"`
	MarketCapUpdate *MarketCapUpdate       `protobuf:"bytes,4,opt,name=MarketCapUpdate,proto3,oneof" json:"MarketCapUpdate,omitempty"`
	Ranking         *Ranking               `protobuf:"bytes,5,opt,name=Ranking,proto3" json:"Ranking,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TokenUpdate) Reset() {
	*x = TokenUpdate{}
	mi := &file_market_price_index_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUpdate) ProtoMessage() {}

func (x *TokenUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUpdate.ProtoReflect.Descriptor instead.
func (*TokenUpdate) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{12}
}

func (x *TokenUpdate) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *TokenUpdate) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *TokenUpdate) GetPriceUpdate() *PriceUpdate {
	if x != nil {
		return x.PriceUpdate
	}
	return nil
}

func (x *TokenUpdate) GetMarketCapUpdate() *MarketCapUpdate {
	if x != nil {
		return x.MarketCapUpdate
	}
	return nil
}

func (x *TokenUpdate) GetRanking() *Ranking {
	if x != nil {
		return x.Ranking
	}
	return nil
}

type Ranking struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Position      uint32                 `protobuf:"varint,1,opt,name=Position,proto3" json:"Position,omitempty"`
	Weight        float32                `protobuf:"fixed32,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ranking) Reset() {
	*x = Ranking{}
	mi := &file_market_price_index_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ranking) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ranking) ProtoMessage() {}

func (x *Ranking) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ranking.ProtoReflect.Descriptor instead.
func (*Ranking) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{13}
}

func (x *Ranking) GetPosition() uint32 {
	if x != nil {
		return x.Position
	}
	return 0
}

func (x *Ranking) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

type PairUpdate struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Currency                 *Currency              `protobuf:"bytes,1,opt,name=Currency,proto3" json:"Currency,omitempty"`
	QuoteCurrency            *Currency              `protobuf:"bytes,2,opt,name=QuoteCurrency,proto3" json:"QuoteCurrency,omitempty"`
	Token                    *Token                 `protobuf:"bytes,3,opt,name=Token,proto3" json:"Token,omitempty"`
	QuoteToken               *Token                 `protobuf:"bytes,4,opt,name=QuoteToken,proto3" json:"QuoteToken,omitempty"`
	Market                   *Market                `protobuf:"bytes,5,opt,name=Market,proto3" json:"Market,omitempty"`
	PriceUpdate              *PriceUpdate           `protobuf:"bytes,6,opt,name=PriceUpdate,proto3" json:"PriceUpdate,omitempty"`
	PriceUpdateInQuoteTokens *PriceUpdate           `protobuf:"bytes,7,opt,name=PriceUpdateInQuoteTokens,proto3" json:"PriceUpdateInQuoteTokens,omitempty"`
	MarketCapUpdate          *MarketCapUpdate       `protobuf:"bytes,8,opt,name=MarketCapUpdate,proto3,oneof" json:"MarketCapUpdate,omitempty"`
	Ranking                  *Ranking               `protobuf:"bytes,9,opt,name=Ranking,proto3" json:"Ranking,omitempty"`
	Pool                     *Pool                  `protobuf:"bytes,10,opt,name=Pool,proto3" json:"Pool,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PairUpdate) Reset() {
	*x = PairUpdate{}
	mi := &file_market_price_index_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairUpdate) ProtoMessage() {}

func (x *PairUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairUpdate.ProtoReflect.Descriptor instead.
func (*PairUpdate) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{14}
}

func (x *PairUpdate) GetCurrency() *Currency {
	if x != nil {
		return x.Currency
	}
	return nil
}

func (x *PairUpdate) GetQuoteCurrency() *Currency {
	if x != nil {
		return x.QuoteCurrency
	}
	return nil
}

func (x *PairUpdate) GetToken() *Token {
	if x != nil {
		return x.Token
	}
	return nil
}

func (x *PairUpdate) GetQuoteToken() *Token {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *PairUpdate) GetMarket() *Market {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *PairUpdate) GetPriceUpdate() *PriceUpdate {
	if x != nil {
		return x.PriceUpdate
	}
	return nil
}

func (x *PairUpdate) GetPriceUpdateInQuoteTokens() *PriceUpdate {
	if x != nil {
		return x.PriceUpdateInQuoteTokens
	}
	return nil
}

func (x *PairUpdate) GetMarketCapUpdate() *MarketCapUpdate {
	if x != nil {
		return x.MarketCapUpdate
	}
	return nil
}

func (x *PairUpdate) GetRanking() *Ranking {
	if x != nil {
		return x.Ranking
	}
	return nil
}

func (x *PairUpdate) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type PriceIndexMessage struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Time            uint64                 `protobuf:"varint,1,opt,name=Time,proto3" json:"Time,omitempty"`
	CurrencyUpdates []*CurrencyUpdate      `protobuf:"bytes,2,rep,name=CurrencyUpdates,proto3" json:"CurrencyUpdates,omitempty"`
	TokenUpdates    []*TokenUpdate         `protobuf:"bytes,3,rep,name=TokenUpdates,proto3" json:"TokenUpdates,omitempty"`
	PairUpdates     []*PairUpdate          `protobuf:"bytes,4,rep,name=PairUpdates,proto3" json:"PairUpdates,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PriceIndexMessage) Reset() {
	*x = PriceIndexMessage{}
	mi := &file_market_price_index_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceIndexMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceIndexMessage) ProtoMessage() {}

func (x *PriceIndexMessage) ProtoReflect() protoreflect.Message {
	mi := &file_market_price_index_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceIndexMessage.ProtoReflect.Descriptor instead.
func (*PriceIndexMessage) Descriptor() ([]byte, []int) {
	return file_market_price_index_proto_rawDescGZIP(), []int{15}
}

func (x *PriceIndexMessage) GetTime() uint64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *PriceIndexMessage) GetCurrencyUpdates() []*CurrencyUpdate {
	if x != nil {
		return x.CurrencyUpdates
	}
	return nil
}

func (x *PriceIndexMessage) GetTokenUpdates() []*TokenUpdate {
	if x != nil {
		return x.TokenUpdates
	}
	return nil
}

func (x *PriceIndexMessage) GetPairUpdates() []*PairUpdate {
	if x != nil {
		return x.PairUpdates
	}
	return nil
}

var File_market_price_index_proto protoreflect.FileDescriptor

const file_market_price_index_proto_rawDesc = "" +
	"\n" +
	"\x18market/price_index.proto\x12\x13marketdata_messages\x1a\x17market/marketdata.proto\x1a\x11market/pool.proto\"F\n" +
	"\bCurrency\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x16\n" +
	"\x06Symbol\x18\x03 \x01(\tR\x06Symbol\"\xde\x01\n" +
	"\x06Market\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\tR\x02Id\x12\x18\n" +
	"\aNetwork\x18\x02 \x01(\tR\aNetwork\x12\x1e\n" +
	"\n" +
	"NetworkBid\x18\x03 \x01(\tR\n" +
	"NetworkBid\x12\x12\n" +
	"\x04Name\x18\x04 \x01(\tR\x04Name\x12\x18\n" +
	"\aAddress\x18\x05 \x01(\tR\aAddress\x12\x1a\n" +
	"\bProtocol\x18\x06 \x01(\tR\bProtocol\x12&\n" +
	"\x0eProtocolFamily\x18\a \x01(\tR\x0eProtocolFamily\x12\x18\n" +
	"\aProgram\x18\b \x01(\tR\aProgram\"w\n" +
	"\aAmounts\x12\x12\n" +
	"\x04Base\x18\x01 \x01(\x02R\x04Base\x12\x14\n" +
	"\x05Quote\x18\x02 \x01(\x02R\x05Quote\x12\x10\n" +
	"\x03Usd\x18\x03 \x01(\x02R\x03Usd\x120\n" +
	"\x13BaseAttributedToUsd\x18\x04 \x01(\x02R\x13BaseAttributedToUsd\"\x84\x01\n" +
	"\x05Quote\x12C\n" +
	"\rQuoteCurrency\x18\x01 \x01(\v2\x1d.marketdata_messages.CurrencyR\rQuoteCurrency\x126\n" +
	"\aAmounts\x18\x02 \x01(\v2\x1c.marketdata_messages.AmountsR\aAmounts\"R\n" +
	"\fTimeInterval\x12\x1a\n" +
	"\bDuration\x18\x01 \x01(\rR\bDuration\x12\x14\n" +
	"\x05Start\x18\x02 \x01(\rR\x05Start\x12\x10\n" +
	"\x03End\x18\x03 \x01(\rR\x03End\"n\n" +
	"\x04Ohlc\x12\x12\n" +
	"\x04Open\x18\x01 \x01(\x02R\x04Open\x12\x14\n" +
	"\x05Close\x18\x02 \x01(\x02R\x05Close\x12\x12\n" +
	"\x04High\x18\x03 \x01(\x02R\x04High\x12\x10\n" +
	"\x03Low\x18\x04 \x01(\x02R\x03Low\x12\x16\n" +
	"\x06Volume\x18\x05 \x01(\x02R\x06Volume\"\x91\x03\n" +
	"\x13PriceByTimeInterval\x12E\n" +
	"\fTimeInterval\x18\x01 \x01(\v2!.marketdata_messages.TimeIntervalR\fTimeInterval\x126\n" +
	"\aAmounts\x18\x02 \x01(\v2\x1c.marketdata_messages.AmountsR\aAmounts\x12\x1c\n" +
	"\tMeanPrice\x18\x03 \x01(\x02R\tMeanPrice\x120\n" +
	"\x13SimpleMovingAverage\x18\x04 \x01(\x02R\x13SimpleMovingAverage\x12@\n" +
	"\x1bWeightedSimpleMovingAverage\x18\x05 \x01(\x02R\x1bWeightedSimpleMovingAverage\x12:\n" +
	"\x18ExponentialMovingAverage\x18\x06 \x01(\x02R\x18ExponentialMovingAverage\x12-\n" +
	"\x04Ohlc\x18\a \x01(\v2\x19.marketdata_messages.OhlcR\x04Ohlc\"\xd0\x01\n" +
	"\rPriceByVolume\x12\"\n" +
	"\fTargetVolume\x18\x01 \x01(\x02R\fTargetVolume\x12E\n" +
	"\fTimeInterval\x18\x02 \x01(\v2!.marketdata_messages.TimeIntervalR\fTimeInterval\x126\n" +
	"\aAmounts\x18\x03 \x01(\v2\x1c.marketdata_messages.AmountsR\aAmounts\x12\x1c\n" +
	"\tMeanPrice\x18\x04 \x01(\x02R\tMeanPrice\"7\n" +
	"\x0fEstimatedPrices\x12$\n" +
	"\rAdaptivePrice\x18\x01 \x01(\x02R\rAdaptivePrice\"\xaf\x02\n" +
	"\vPriceUpdate\x122\n" +
	"\x06Quotes\x18\x01 \x03(\v2\x1a.marketdata_messages.QuoteR\x06Quotes\x12\\\n" +
	"\x14PriceByTimeIntervals\x18\x02 \x03(\v2(.marketdata_messages.PriceByTimeIntervalR\x14PriceByTimeIntervals\x12J\n" +
	"\x0ePriceByVolumes\x18\x03 \x03(\v2\".marketdata_messages.PriceByVolumeR\x0ePriceByVolumes\x12B\n" +
	"\tEstimates\x18\x04 \x01(\v2$.marketdata_messages.EstimatedPricesR\tEstimates\"\x87\x02\n" +
	"\x0fMarketCapUpdate\x12 \n" +
	"\vTotalSupply\x18\x01 \x01(\x01R\vTotalSupply\x12\x1c\n" +
	"\tMarketCap\x18\x02 \x01(\x01R\tMarketCap\x12:\n" +
	"\x18FullyDilutedValuationUsd\x18\x03 \x01(\x01R\x18FullyDilutedValuationUsd\x121\n" +
	"\x11CirculatingSupply\x18\x04 \x01(\x01H\x00R\x11CirculatingSupply\x88\x01\x01\x12!\n" +
	"\tMaxSupply\x18\x05 \x01(\x01H\x01R\tMaxSupply\x88\x01\x01B\x14\n" +
	"\x12_CirculatingSupplyB\f\n" +
	"\n" +
	"_MaxSupply\"\xf8\x01\n" +
	"\x0eCurrencyUpdate\x129\n" +
	"\bCurrency\x18\x01 \x01(\v2\x1d.marketdata_messages.CurrencyR\bCurrency\x12B\n" +
	"\vPriceUpdate\x18\x02 \x01(\v2 .marketdata_messages.PriceUpdateR\vPriceUpdate\x12S\n" +
	"\x0fMarketCapUpdate\x18\x03 \x01(\v2$.marketdata_messages.MarketCapUpdateH\x00R\x0fMarketCapUpdate\x88\x01\x01B\x12\n" +
	"\x10_MarketCapUpdate\"\xdf\x02\n" +
	"\vTokenUpdate\x129\n" +
	"\bCurrency\x18\x01 \x01(\v2\x1d.marketdata_messages.CurrencyR\bCurrency\x120\n" +
	"\x05Token\x18\x02 \x01(\v2\x1a.marketdata_messages.TokenR\x05Token\x12B\n" +
	"\vPriceUpdate\x18\x03 \x01(\v2 .marketdata_messages.PriceUpdateR\vPriceUpdate\x12S\n" +
	"\x0fMarketCapUpdate\x18\x04 \x01(\v2$.marketdata_messages.MarketCapUpdateH\x00R\x0fMarketCapUpdate\x88\x01\x01\x126\n" +
	"\aRanking\x18\x05 \x01(\v2\x1c.marketdata_messages.RankingR\aRankingB\x12\n" +
	"\x10_MarketCapUpdate\"=\n" +
	"\aRanking\x12\x1a\n" +
	"\bPosition\x18\x01 \x01(\rR\bPosition\x12\x16\n" +
	"\x06Weight\x18\x02 \x01(\x02R\x06Weight\"\xa1\x05\n" +
	"\n" +
	"PairUpdate\x129\n" +
	"\bCurrency\x18\x01 \x01(\v2\x1d.marketdata_messages.CurrencyR\bCurrency\x12C\n" +
	"\rQuoteCurrency\x18\x02 \x01(\v2\x1d.marketdata_messages.CurrencyR\rQuoteCurrency\x120\n" +
	"\x05Token\x18\x03 \x01(\v2\x1a.marketdata_messages.TokenR\x05Token\x12:\n" +
	"\n" +
	"QuoteToken\x18\x04 \x01(\v2\x1a.marketdata_messages.TokenR\n" +
	"QuoteToken\x123\n" +
	"\x06Market\x18\x05 \x01(\v2\x1b.marketdata_messages.MarketR\x06Market\x12B\n" +
	"\vPriceUpdate\x18\x06 \x01(\v2 .marketdata_messages.PriceUpdateR\vPriceUpdate\x12\\\n" +
	"\x18PriceUpdateInQuoteTokens\x18\a \x01(\v2 .marketdata_messages.PriceUpdateR\x18PriceUpdateInQuoteTokens\x12S\n" +
	"\x0fMarketCapUpdate\x18\b \x01(\v2$.marketdata_messages.MarketCapUpdateH\x00R\x0fMarketCapUpdate\x88\x01\x01\x126\n" +
	"\aRanking\x18\t \x01(\v2\x1c.marketdata_messages.RankingR\aRanking\x12-\n" +
	"\x04Pool\x18\n" +
	" \x01(\v2\x19.marketdata_messages.PoolR\x04PoolB\x12\n" +
	"\x10_MarketCapUpdate\"\xff\x01\n" +
	"\x11PriceIndexMessage\x12\x12\n" +
	"\x04Time\x18\x01 \x01(\x04R\x04Time\x12M\n" +
	"\x0fCurrencyUpdates\x18\x02 \x03(\v2#.marketdata_messages.CurrencyUpdateR\x0fCurrencyUpdates\x12D\n" +
	"\fTokenUpdates\x18\x03 \x03(\v2 .marketdata_messages.TokenUpdateR\fTokenUpdates\x12A\n" +
	"\vPairUpdates\x18\x04 \x03(\v2\x1f.marketdata_messages.PairUpdateR\vPairUpdatesb\x06proto3"

var (
	file_market_price_index_proto_rawDescOnce sync.Once
	file_market_price_index_proto_rawDescData []byte
)

func file_market_price_index_proto_rawDescGZIP() []byte {
	file_market_price_index_proto_rawDescOnce.Do(func() {
		file_market_price_index_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_price_index_proto_rawDesc), len(file_market_price_index_proto_rawDesc)))
	})
	return file_market_price_index_proto_rawDescData
}

var file_market_price_index_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_market_price_index_proto_goTypes = []any{
	(*Currency)(nil),            // 0: marketdata_messages.Currency
	(*Market)(nil),              // 1: marketdata_messages.Market
	(*Amounts)(nil),             // 2: marketdata_messages.Amounts
	(*Quote)(nil),               // 3: marketdata_messages.Quote
	(*TimeInterval)(nil),        // 4: marketdata_messages.TimeInterval
	(*Ohlc)(nil),                // 5: marketdata_messages.Ohlc
	(*PriceByTimeInterval)(nil), // 6: marketdata_messages.PriceByTimeInterval
	(*PriceByVolume)(nil),       // 7: marketdata_messages.PriceByVolume
	(*EstimatedPrices)(nil),     // 8: marketdata_messages.EstimatedPrices
	(*PriceUpdate)(nil),         // 9: marketdata_messages.PriceUpdate
	(*MarketCapUpdate)(nil),     // 10: marketdata_messages.MarketCapUpdate
	(*CurrencyUpdate)(nil),      // 11: marketdata_messages.CurrencyUpdate
	(*TokenUpdate)(nil),         // 12: marketdata_messages.TokenUpdate
	(*Ranking)(nil),             // 13: marketdata_messages.Ranking
	(*PairUpdate)(nil),          // 14: marketdata_messages.PairUpdate
	(*PriceIndexMessage)(nil),   // 15: marketdata_messages.PriceIndexMessage
	(*Token)(nil),               // 16: marketdata_messages.Token
	(*Pool)(nil),                // 17: marketdata_messages.Pool
}
var file_market_price_index_proto_depIdxs = []int32{
	0,  // 0: marketdata_messages.Quote.QuoteCurrency:type_name -> marketdata_messages.Currency
	2,  // 1: marketdata_messages.Quote.Amounts:type_name -> marketdata_messages.Amounts
	4,  // 2: marketdata_messages.PriceByTimeInterval.TimeInterval:type_name -> marketdata_messages.TimeInterval
	2,  // 3: marketdata_messages.PriceByTimeInterval.Amounts:type_name -> marketdata_messages.Amounts
	5,  // 4: marketdata_messages.PriceByTimeInterval.Ohlc:type_name -> marketdata_messages.Ohlc
	4,  // 5: marketdata_messages.PriceByVolume.TimeInterval:type_name -> marketdata_messages.TimeInterval
	2,  // 6: marketdata_messages.PriceByVolume.Amounts:type_name -> marketdata_messages.Amounts
	3,  // 7: marketdata_messages.PriceUpdate.Quotes:type_name -> marketdata_messages.Quote
	6,  // 8: marketdata_messages.PriceUpdate.PriceByTimeIntervals:type_name -> marketdata_messages.PriceByTimeInterval
	7,  // 9: marketdata_messages.PriceUpdate.PriceByVolumes:type_name -> marketdata_messages.PriceByVolume
	8,  // 10: marketdata_messages.PriceUpdate.Estimates:type_name -> marketdata_messages.EstimatedPrices
	0,  // 11: marketdata_messages.CurrencyUpdate.Currency:type_name -> marketdata_messages.Currency
	9,  // 12: marketdata_messages.CurrencyUpdate.PriceUpdate:type_name -> marketdata_messages.PriceUpdate
	10, // 13: marketdata_messages.CurrencyUpdate.MarketCapUpdate:type_name -> marketdata_messages.MarketCapUpdate
	0,  // 14: marketdata_messages.TokenUpdate.Currency:type_name -> marketdata_messages.Currency
	16, // 15: marketdata_messages.TokenUpdate.Token:type_name -> marketdata_messages.Token
	9,  // 16: marketdata_messages.TokenUpdate.PriceUpdate:type_name -> marketdata_messages.PriceUpdate
	10, // 17: marketdata_messages.TokenUpdate.MarketCapUpdate:type_name -> marketdata_messages.MarketCapUpdate
	13, // 18: marketdata_messages.TokenUpdate.Ranking:type_name -> marketdata_messages.Ranking
	0,  // 19: marketdata_messages.PairUpdate.Currency:type_name -> marketdata_messages.Currency
	0,  // 20: marketdata_messages.PairUpdate.QuoteCurrency:type_name -> marketdata_messages.Currency
	16, // 21: marketdata_messages.PairUpdate.Token:type_name -> marketdata_messages.Token
	16, // 22: marketdata_messages.PairUpdate.QuoteToken:type_name -> marketdata_messages.Token
	1,  // 23: marketdata_messages.PairUpdate.Market:type_name -> marketdata_messages.Market
	9,  // 24: marketdata_messages.PairUpdate.PriceUpdate:type_name -> marketdata_messages.PriceUpdate
	9,  // 25: marketdata_messages.PairUpdate.PriceUpdateInQuoteTokens:type_name -> marketdata_messages.PriceUpdate
	10, // 26: marketdata_messages.PairUpdate.MarketCapUpdate:type_name -> marketdata_messages.MarketCapUpdate
	13, // 27: marketdata_messages.PairUpdate.Ranking:type_name -> marketdata_messages.Ranking
	17, // 28: marketdata_messages.PairUpdate.Pool:type_name -> marketdata_messages.Pool
	11, // 29: marketdata_messages.PriceIndexMessage.CurrencyUpdates:type_name -> marketdata_messages.CurrencyUpdate
	12, // 30: marketdata_messages.PriceIndexMessage.TokenUpdates:type_name -> marketdata_messages.TokenUpdate
	14, // 31: marketdata_messages.PriceIndexMessage.PairUpdates:type_name -> marketdata_messages.PairUpdate
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_market_price_index_proto_init() }
func file_market_price_index_proto_init() {
	if File_market_price_index_proto != nil {
		return
	}
	file_market_marketdata_proto_init()
	file_market_pool_proto_init()
	file_market_price_index_proto_msgTypes[10].OneofWrappers = []any{}
	file_market_price_index_proto_msgTypes[11].OneofWrappers = []any{}
	file_market_price_index_proto_msgTypes[12].OneofWrappers = []any{}
	file_market_price_index_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_price_index_proto_rawDesc), len(file_market_price_index_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_market_price_index_proto_goTypes,
		DependencyIndexes: file_market_price_index_proto_depIdxs,
		MessageInfos:      file_market_price_index_proto_msgTypes,
	}.Build()
	File_market_price_index_proto = out.File
	file_market_price_index_proto_goTypes = nil
	file_market_price_index_proto_depIdxs = nil
}
