// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: evm/parsed_abi_block_message.proto

package evm_messages

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ParsedAbiSignature_SignatureType int32

const (
	ParsedAbiSignature_FUNCTION    ParsedAbiSignature_SignatureType = 0
	ParsedAbiSignature_CONSTRUCTOR ParsedAbiSignature_SignatureType = 1
	ParsedAbiSignature_FALLBACK    ParsedAbiSignature_SignatureType = 2
	ParsedAbiSignature_RECEIVE     ParsedAbiSignature_SignatureType = 3
	ParsedAbiSignature_LOG         ParsedAbiSignature_SignatureType = 4
)

// Enum value maps for ParsedAbiSignature_SignatureType.
var (
	ParsedAbiSignature_SignatureType_name = map[int32]string{
		0: "FUNCTION",
		1: "CONSTRUCTOR",
		2: "FALLBACK",
		3: "RECEIVE",
		4: "LOG",
	}
	ParsedAbiSignature_SignatureType_value = map[string]int32{
		"FUNCTION":    0,
		"CONSTRUCTOR": 1,
		"FALLBACK":    2,
		"RECEIVE":     3,
		"LOG":         4,
	}
)

func (x ParsedAbiSignature_SignatureType) Enum() *ParsedAbiSignature_SignatureType {
	p := new(ParsedAbiSignature_SignatureType)
	*p = x
	return p
}

func (x ParsedAbiSignature_SignatureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ParsedAbiSignature_SignatureType) Descriptor() protoreflect.EnumDescriptor {
	return file_evm_parsed_abi_block_message_proto_enumTypes[0].Descriptor()
}

func (ParsedAbiSignature_SignatureType) Type() protoreflect.EnumType {
	return &file_evm_parsed_abi_block_message_proto_enumTypes[0]
}

func (x ParsedAbiSignature_SignatureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ParsedAbiSignature_SignatureType.Descriptor instead.
func (ParsedAbiSignature_SignatureType) EnumDescriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{3, 0}
}

type ArgumentValue struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Type     string                 `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	IsHashed bool                   `protobuf:"varint,2,opt,name=IsHashed,proto3" json:"IsHashed,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*ArgumentValue_String_
	//	*ArgumentValue_Bytes
	//	*ArgumentValue_UInt
	//	*ArgumentValue_Int
	//	*ArgumentValue_Bool
	//	*ArgumentValue_Array
	//	*ArgumentValue_Tuple
	Value         isArgumentValue_Value `protobuf_oneof:"Value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgumentValue) Reset() {
	*x = ArgumentValue{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgumentValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentValue) ProtoMessage() {}

func (x *ArgumentValue) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentValue.ProtoReflect.Descriptor instead.
func (*ArgumentValue) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{0}
}

func (x *ArgumentValue) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ArgumentValue) GetIsHashed() bool {
	if x != nil {
		return x.IsHashed
	}
	return false
}

func (x *ArgumentValue) GetValue() isArgumentValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ArgumentValue) GetString_() string {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *ArgumentValue) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *ArgumentValue) GetUInt() uint64 {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_UInt); ok {
			return x.UInt
		}
	}
	return 0
}

func (x *ArgumentValue) GetInt() int64 {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_Int); ok {
			return x.Int
		}
	}
	return 0
}

func (x *ArgumentValue) GetBool() bool {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_Bool); ok {
			return x.Bool
		}
	}
	return false
}

func (x *ArgumentValue) GetArray() *ArgumentArray {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_Array); ok {
			return x.Array
		}
	}
	return nil
}

func (x *ArgumentValue) GetTuple() *ArgumentTuple {
	if x != nil {
		if x, ok := x.Value.(*ArgumentValue_Tuple); ok {
			return x.Tuple
		}
	}
	return nil
}

type isArgumentValue_Value interface {
	isArgumentValue_Value()
}

type ArgumentValue_String_ struct {
	String_ string `protobuf:"bytes,3,opt,name=String,proto3,oneof"`
}

type ArgumentValue_Bytes struct {
	Bytes []byte `protobuf:"bytes,4,opt,name=Bytes,proto3,oneof"`
}

type ArgumentValue_UInt struct {
	UInt uint64 `protobuf:"varint,5,opt,name=UInt,proto3,oneof"`
}

type ArgumentValue_Int struct {
	Int int64 `protobuf:"varint,6,opt,name=Int,proto3,oneof"`
}

type ArgumentValue_Bool struct {
	Bool bool `protobuf:"varint,7,opt,name=Bool,proto3,oneof"`
}

type ArgumentValue_Array struct {
	Array *ArgumentArray `protobuf:"bytes,10,opt,name=Array,proto3,oneof"`
}

type ArgumentValue_Tuple struct {
	Tuple *ArgumentTuple `protobuf:"bytes,11,opt,name=Tuple,proto3,oneof"`
}

func (*ArgumentValue_String_) isArgumentValue_Value() {}

func (*ArgumentValue_Bytes) isArgumentValue_Value() {}

func (*ArgumentValue_UInt) isArgumentValue_Value() {}

func (*ArgumentValue_Int) isArgumentValue_Value() {}

func (*ArgumentValue_Bool) isArgumentValue_Value() {}

func (*ArgumentValue_Array) isArgumentValue_Value() {}

func (*ArgumentValue_Tuple) isArgumentValue_Value() {}

type ArgumentArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ArgumentValue       `protobuf:"bytes,1,rep,name=Elements,proto3" json:"Elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgumentArray) Reset() {
	*x = ArgumentArray{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgumentArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentArray) ProtoMessage() {}

func (x *ArgumentArray) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentArray.ProtoReflect.Descriptor instead.
func (*ArgumentArray) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{1}
}

func (x *ArgumentArray) GetElements() []*ArgumentValue {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ArgumentTuple struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Elements      []*ArgumentValue       `protobuf:"bytes,2,rep,name=Elements,proto3" json:"Elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArgumentTuple) Reset() {
	*x = ArgumentTuple{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArgumentTuple) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArgumentTuple) ProtoMessage() {}

func (x *ArgumentTuple) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArgumentTuple.ProtoReflect.Descriptor instead.
func (*ArgumentTuple) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{2}
}

func (x *ArgumentTuple) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArgumentTuple) GetElements() []*ArgumentValue {
	if x != nil {
		return x.Elements
	}
	return nil
}

type ParsedAbiSignature struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Parsed        bool                             `protobuf:"varint,1,opt,name=Parsed,proto3" json:"Parsed,omitempty"`
	Name          string                           `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Signature     string                           `protobuf:"bytes,3,opt,name=Signature,proto3" json:"Signature,omitempty"`
	Abi           string                           `protobuf:"bytes,4,opt,name=Abi,proto3" json:"Abi,omitempty"`
	SignatureHash []byte                           `protobuf:"bytes,5,opt,name=SignatureHash,proto3" json:"SignatureHash,omitempty"`
	Type          ParsedAbiSignature_SignatureType `protobuf:"varint,6,opt,name=Type,proto3,enum=evm_messages.ParsedAbiSignature_SignatureType" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiSignature) Reset() {
	*x = ParsedAbiSignature{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiSignature) ProtoMessage() {}

func (x *ParsedAbiSignature) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiSignature.ProtoReflect.Descriptor instead.
func (*ParsedAbiSignature) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{3}
}

func (x *ParsedAbiSignature) GetParsed() bool {
	if x != nil {
		return x.Parsed
	}
	return false
}

func (x *ParsedAbiSignature) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParsedAbiSignature) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *ParsedAbiSignature) GetAbi() string {
	if x != nil {
		return x.Abi
	}
	return ""
}

func (x *ParsedAbiSignature) GetSignatureHash() []byte {
	if x != nil {
		return x.SignatureHash
	}
	return nil
}

func (x *ParsedAbiSignature) GetType() ParsedAbiSignature_SignatureType {
	if x != nil {
		return x.Type
	}
	return ParsedAbiSignature_FUNCTION
}

type ParsedArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Indexed       bool                   `protobuf:"varint,2,opt,name=Indexed,proto3" json:"Indexed,omitempty"`
	Value         *ArgumentValue         `protobuf:"bytes,3,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedArgument) Reset() {
	*x = ParsedArgument{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedArgument) ProtoMessage() {}

func (x *ParsedArgument) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedArgument.ProtoReflect.Descriptor instead.
func (*ParsedArgument) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{4}
}

func (x *ParsedArgument) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParsedArgument) GetIndexed() bool {
	if x != nil {
		return x.Indexed
	}
	return false
}

func (x *ParsedArgument) GetValue() *ArgumentValue {
	if x != nil {
		return x.Value
	}
	return nil
}

type ParsedAbiLogHeader struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Index             uint32                 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	EnterIndex        uint32                 `protobuf:"varint,2,opt,name=EnterIndex,proto3" json:"EnterIndex,omitempty"`
	ExitIndex         uint32                 `protobuf:"varint,3,opt,name=ExitIndex,proto3" json:"ExitIndex,omitempty"`
	LogAfterCallIndex uint32                 `protobuf:"varint,4,opt,name=LogAfterCallIndex,proto3" json:"LogAfterCallIndex,omitempty"`
	Pc                uint64                 `protobuf:"varint,5,opt,name=Pc,proto3" json:"Pc,omitempty"`
	SmartContract     []byte                 `protobuf:"bytes,6,opt,name=SmartContract,proto3" json:"SmartContract,omitempty"`
	Signature         *ParsedAbiSignature    `protobuf:"bytes,7,opt,name=Signature,proto3" json:"Signature,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ParsedAbiLogHeader) Reset() {
	*x = ParsedAbiLogHeader{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiLogHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiLogHeader) ProtoMessage() {}

func (x *ParsedAbiLogHeader) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiLogHeader.ProtoReflect.Descriptor instead.
func (*ParsedAbiLogHeader) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{5}
}

func (x *ParsedAbiLogHeader) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ParsedAbiLogHeader) GetEnterIndex() uint32 {
	if x != nil {
		return x.EnterIndex
	}
	return 0
}

func (x *ParsedAbiLogHeader) GetExitIndex() uint32 {
	if x != nil {
		return x.ExitIndex
	}
	return 0
}

func (x *ParsedAbiLogHeader) GetLogAfterCallIndex() uint32 {
	if x != nil {
		return x.LogAfterCallIndex
	}
	return 0
}

func (x *ParsedAbiLogHeader) GetPc() uint64 {
	if x != nil {
		return x.Pc
	}
	return 0
}

func (x *ParsedAbiLogHeader) GetSmartContract() []byte {
	if x != nil {
		return x.SmartContract
	}
	return nil
}

func (x *ParsedAbiLogHeader) GetSignature() *ParsedAbiSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ParsedAbiLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *LogHeader             `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Topics        []*Topic               `protobuf:"bytes,2,rep,name=Topics,proto3" json:"Topics,omitempty"`
	Parsed        *ParsedAbiLogHeader    `protobuf:"bytes,3,opt,name=Parsed,proto3" json:"Parsed,omitempty"`
	Arguments     []*ParsedArgument      `protobuf:"bytes,4,rep,name=Arguments,proto3" json:"Arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiLog) Reset() {
	*x = ParsedAbiLog{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiLog) ProtoMessage() {}

func (x *ParsedAbiLog) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiLog.ProtoReflect.Descriptor instead.
func (*ParsedAbiLog) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{6}
}

func (x *ParsedAbiLog) GetHeader() *LogHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedAbiLog) GetTopics() []*Topic {
	if x != nil {
		return x.Topics
	}
	return nil
}

func (x *ParsedAbiLog) GetParsed() *ParsedAbiLogHeader {
	if x != nil {
		return x.Parsed
	}
	return nil
}

func (x *ParsedAbiLog) GetArguments() []*ParsedArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ParsedStateChange struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	EnterIndex           uint32                 `protobuf:"varint,1,opt,name=EnterIndex,proto3" json:"EnterIndex,omitempty"`
	ExitIndex            uint32                 `protobuf:"varint,2,opt,name=ExitIndex,proto3" json:"ExitIndex,omitempty"`
	ChangeAfterCallIndex uint32                 `protobuf:"varint,3,opt,name=ChangeAfterCallIndex,proto3" json:"ChangeAfterCallIndex,omitempty"`
	Pc                   uint64                 `protobuf:"varint,4,opt,name=Pc,proto3" json:"Pc,omitempty"`
	Address              []byte                 `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	Location             []byte                 `protobuf:"bytes,6,opt,name=Location,proto3" json:"Location,omitempty"`
	Value                []byte                 `protobuf:"bytes,7,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParsedStateChange) Reset() {
	*x = ParsedStateChange{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedStateChange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedStateChange) ProtoMessage() {}

func (x *ParsedStateChange) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedStateChange.ProtoReflect.Descriptor instead.
func (*ParsedStateChange) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{7}
}

func (x *ParsedStateChange) GetEnterIndex() uint32 {
	if x != nil {
		return x.EnterIndex
	}
	return 0
}

func (x *ParsedStateChange) GetExitIndex() uint32 {
	if x != nil {
		return x.ExitIndex
	}
	return 0
}

func (x *ParsedStateChange) GetChangeAfterCallIndex() uint32 {
	if x != nil {
		return x.ChangeAfterCallIndex
	}
	return 0
}

func (x *ParsedStateChange) GetPc() uint64 {
	if x != nil {
		return x.Pc
	}
	return 0
}

func (x *ParsedStateChange) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *ParsedStateChange) GetLocation() []byte {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *ParsedStateChange) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ParsedAbiCallHeader struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Index         uint32                 `protobuf:"varint,1,opt,name=Index,proto3" json:"Index,omitempty"`
	Depth         uint32                 `protobuf:"varint,2,opt,name=Depth,proto3" json:"Depth,omitempty"`
	EnterIndex    uint32                 `protobuf:"varint,3,opt,name=EnterIndex,proto3" json:"EnterIndex,omitempty"`
	ExitIndex     uint32                 `protobuf:"varint,4,opt,name=ExitIndex,proto3" json:"ExitIndex,omitempty"`
	CallerIndex   int32                  `protobuf:"varint,5,opt,name=CallerIndex,proto3" json:"CallerIndex,omitempty"`
	InternalCalls uint32                 `protobuf:"varint,6,opt,name=InternalCalls,proto3" json:"InternalCalls,omitempty"`
	CallPath      []uint32               `protobuf:"varint,7,rep,packed,name=CallPath,proto3" json:"CallPath,omitempty"`
	From          []byte                 `protobuf:"bytes,8,opt,name=From,proto3" json:"From,omitempty"`
	To            []byte                 `protobuf:"bytes,9,opt,name=To,proto3" json:"To,omitempty"`
	Create        bool                   `protobuf:"varint,10,opt,name=Create,proto3" json:"Create,omitempty"`
	Input         []byte                 `protobuf:"bytes,11,opt,name=Input,proto3" json:"Input,omitempty"`
	Gas           uint64                 `protobuf:"varint,12,opt,name=Gas,proto3" json:"Gas,omitempty"`
	Value         []byte                 `protobuf:"bytes,13,opt,name=Value,proto3" json:"Value,omitempty"`
	Output        []byte                 `protobuf:"bytes,14,opt,name=Output,proto3" json:"Output,omitempty"`
	GasUsed       uint64                 `protobuf:"varint,15,opt,name=GasUsed,proto3" json:"GasUsed,omitempty"`
	Error         string                 `protobuf:"bytes,16,opt,name=Error,proto3" json:"Error,omitempty"`
	Opcode        *Opcode                `protobuf:"bytes,17,opt,name=Opcode,proto3" json:"Opcode,omitempty"`
	SelfDestruct  bool                   `protobuf:"varint,18,opt,name=SelfDestruct,proto3" json:"SelfDestruct,omitempty"`
	Delegated     bool                   `protobuf:"varint,19,opt,name=Delegated,proto3" json:"Delegated,omitempty"`
	Success       bool                   `protobuf:"varint,20,opt,name=Success,proto3" json:"Success,omitempty"`
	Reverted      bool                   `protobuf:"varint,21,opt,name=Reverted,proto3" json:"Reverted,omitempty"`
	Signature     *ParsedAbiSignature    `protobuf:"bytes,22,opt,name=Signature,proto3" json:"Signature,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiCallHeader) Reset() {
	*x = ParsedAbiCallHeader{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiCallHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiCallHeader) ProtoMessage() {}

func (x *ParsedAbiCallHeader) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiCallHeader.ProtoReflect.Descriptor instead.
func (*ParsedAbiCallHeader) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{8}
}

func (x *ParsedAbiCallHeader) GetIndex() uint32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetEnterIndex() uint32 {
	if x != nil {
		return x.EnterIndex
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetExitIndex() uint32 {
	if x != nil {
		return x.ExitIndex
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetCallerIndex() int32 {
	if x != nil {
		return x.CallerIndex
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetInternalCalls() uint32 {
	if x != nil {
		return x.InternalCalls
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetCallPath() []uint32 {
	if x != nil {
		return x.CallPath
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetFrom() []byte {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetTo() []byte {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetCreate() bool {
	if x != nil {
		return x.Create
	}
	return false
}

func (x *ParsedAbiCallHeader) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetGasUsed() uint64 {
	if x != nil {
		return x.GasUsed
	}
	return 0
}

func (x *ParsedAbiCallHeader) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ParsedAbiCallHeader) GetOpcode() *Opcode {
	if x != nil {
		return x.Opcode
	}
	return nil
}

func (x *ParsedAbiCallHeader) GetSelfDestruct() bool {
	if x != nil {
		return x.SelfDestruct
	}
	return false
}

func (x *ParsedAbiCallHeader) GetDelegated() bool {
	if x != nil {
		return x.Delegated
	}
	return false
}

func (x *ParsedAbiCallHeader) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParsedAbiCallHeader) GetReverted() bool {
	if x != nil {
		return x.Reverted
	}
	return false
}

func (x *ParsedAbiCallHeader) GetSignature() *ParsedAbiSignature {
	if x != nil {
		return x.Signature
	}
	return nil
}

type ParsedAbiCall struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *ParsedAbiCallHeader   `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
	Arguments     []*ParsedArgument      `protobuf:"bytes,2,rep,name=Arguments,proto3" json:"Arguments,omitempty"`
	ReturnValues  []*ParsedArgument      `protobuf:"bytes,3,rep,name=ReturnValues,proto3" json:"ReturnValues,omitempty"`
	Logs          []*ParsedAbiLog        `protobuf:"bytes,4,rep,name=Logs,proto3" json:"Logs,omitempty"`
	StateChanges  []*ParsedStateChange   `protobuf:"bytes,5,rep,name=StateChanges,proto3" json:"StateChanges,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiCall) Reset() {
	*x = ParsedAbiCall{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiCall) ProtoMessage() {}

func (x *ParsedAbiCall) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiCall.ProtoReflect.Descriptor instead.
func (*ParsedAbiCall) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{9}
}

func (x *ParsedAbiCall) GetHeader() *ParsedAbiCallHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedAbiCall) GetArguments() []*ParsedArgument {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *ParsedAbiCall) GetReturnValues() []*ParsedArgument {
	if x != nil {
		return x.ReturnValues
	}
	return nil
}

func (x *ParsedAbiCall) GetLogs() []*ParsedAbiLog {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ParsedAbiCall) GetStateChanges() []*ParsedStateChange {
	if x != nil {
		return x.StateChanges
	}
	return nil
}

type TransactionFee struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SenderFee         []byte                 `protobuf:"bytes,1,opt,name=SenderFee,proto3" json:"SenderFee,omitempty"`
	PriorityFeePerGas []byte                 `protobuf:"bytes,2,opt,name=PriorityFeePerGas,proto3" json:"PriorityFeePerGas,omitempty"`
	EffectiveGasPrice []byte                 `protobuf:"bytes,3,opt,name=EffectiveGasPrice,proto3" json:"EffectiveGasPrice,omitempty"`
	GasRefund         uint64                 `protobuf:"varint,4,opt,name=GasRefund,proto3" json:"GasRefund,omitempty"`
	Burnt             []byte                 `protobuf:"bytes,5,opt,name=Burnt,proto3" json:"Burnt,omitempty"`
	Savings           []byte                 `protobuf:"bytes,6,opt,name=Savings,proto3" json:"Savings,omitempty"`
	MinerReward       []byte                 `protobuf:"bytes,7,opt,name=MinerReward,proto3" json:"MinerReward,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TransactionFee) Reset() {
	*x = TransactionFee{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransactionFee) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransactionFee) ProtoMessage() {}

func (x *TransactionFee) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransactionFee.ProtoReflect.Descriptor instead.
func (*TransactionFee) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{10}
}

func (x *TransactionFee) GetSenderFee() []byte {
	if x != nil {
		return x.SenderFee
	}
	return nil
}

func (x *TransactionFee) GetPriorityFeePerGas() []byte {
	if x != nil {
		return x.PriorityFeePerGas
	}
	return nil
}

func (x *TransactionFee) GetEffectiveGasPrice() []byte {
	if x != nil {
		return x.EffectiveGasPrice
	}
	return nil
}

func (x *TransactionFee) GetGasRefund() uint64 {
	if x != nil {
		return x.GasRefund
	}
	return 0
}

func (x *TransactionFee) GetBurnt() []byte {
	if x != nil {
		return x.Burnt
	}
	return nil
}

func (x *TransactionFee) GetSavings() []byte {
	if x != nil {
		return x.Savings
	}
	return nil
}

func (x *TransactionFee) GetMinerReward() []byte {
	if x != nil {
		return x.MinerReward
	}
	return nil
}

type ParsedAbiTransactionStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
	EndError      string                 `protobuf:"bytes,2,opt,name=EndError,proto3" json:"EndError,omitempty"`
	FaultError    string                 `protobuf:"bytes,3,opt,name=FaultError,proto3" json:"FaultError,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiTransactionStatus) Reset() {
	*x = ParsedAbiTransactionStatus{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiTransactionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiTransactionStatus) ProtoMessage() {}

func (x *ParsedAbiTransactionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiTransactionStatus.ProtoReflect.Descriptor instead.
func (*ParsedAbiTransactionStatus) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{11}
}

func (x *ParsedAbiTransactionStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ParsedAbiTransactionStatus) GetEndError() string {
	if x != nil {
		return x.EndError
	}
	return ""
}

func (x *ParsedAbiTransactionStatus) GetFaultError() string {
	if x != nil {
		return x.FaultError
	}
	return ""
}

type ParsedAbiTransaction struct {
	state                protoimpl.MessageState      `protogen:"open.v1"`
	TransactionHeader    *TransactionHeader          `protobuf:"bytes,1,opt,name=TransactionHeader,proto3" json:"TransactionHeader,omitempty"`
	ReceiptHeader        *ReceiptHeader              `protobuf:"bytes,2,opt,name=ReceiptHeader,proto3" json:"ReceiptHeader,omitempty"`
	TransactionFee       *TransactionFee             `protobuf:"bytes,3,opt,name=TransactionFee,proto3" json:"TransactionFee,omitempty"`
	TransactionStatus    *ParsedAbiTransactionStatus `protobuf:"bytes,4,opt,name=TransactionStatus,proto3" json:"TransactionStatus,omitempty"`
	Calls                []*ParsedAbiCall            `protobuf:"bytes,5,rep,name=Calls,proto3" json:"Calls,omitempty"`
	Signature            *Signature                  `protobuf:"bytes,6,opt,name=Signature,proto3" json:"Signature,omitempty"`
	TokenBalanceUpdates  []*TokenBalanceUpdate       `protobuf:"bytes,7,rep,name=TokenBalanceUpdates,proto3" json:"TokenBalanceUpdates,omitempty"`
	NativeBalanceUpdates []*NativeBalanceUpdate      `protobuf:"bytes,8,rep,name=NativeBalanceUpdates,proto3" json:"NativeBalanceUpdates,omitempty"`
	StorageChanges       []*StorageChange            `protobuf:"bytes,9,rep,name=StorageChanges,proto3" json:"StorageChanges,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ParsedAbiTransaction) Reset() {
	*x = ParsedAbiTransaction{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiTransaction) ProtoMessage() {}

func (x *ParsedAbiTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiTransaction.ProtoReflect.Descriptor instead.
func (*ParsedAbiTransaction) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{12}
}

func (x *ParsedAbiTransaction) GetTransactionHeader() *TransactionHeader {
	if x != nil {
		return x.TransactionHeader
	}
	return nil
}

func (x *ParsedAbiTransaction) GetReceiptHeader() *ReceiptHeader {
	if x != nil {
		return x.ReceiptHeader
	}
	return nil
}

func (x *ParsedAbiTransaction) GetTransactionFee() *TransactionFee {
	if x != nil {
		return x.TransactionFee
	}
	return nil
}

func (x *ParsedAbiTransaction) GetTransactionStatus() *ParsedAbiTransactionStatus {
	if x != nil {
		return x.TransactionStatus
	}
	return nil
}

func (x *ParsedAbiTransaction) GetCalls() []*ParsedAbiCall {
	if x != nil {
		return x.Calls
	}
	return nil
}

func (x *ParsedAbiTransaction) GetSignature() *Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *ParsedAbiTransaction) GetTokenBalanceUpdates() []*TokenBalanceUpdate {
	if x != nil {
		return x.TokenBalanceUpdates
	}
	return nil
}

func (x *ParsedAbiTransaction) GetNativeBalanceUpdates() []*NativeBalanceUpdate {
	if x != nil {
		return x.NativeBalanceUpdates
	}
	return nil
}

func (x *ParsedAbiTransaction) GetStorageChanges() []*StorageChange {
	if x != nil {
		return x.StorageChanges
	}
	return nil
}

type MinerReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         []byte                 `protobuf:"bytes,1,opt,name=Total,proto3" json:"Total,omitempty"`
	Static        []byte                 `protobuf:"bytes,2,opt,name=Static,proto3" json:"Static,omitempty"`
	Dynamic       []byte                 `protobuf:"bytes,3,opt,name=Dynamic,proto3" json:"Dynamic,omitempty"`
	TxFees        []byte                 `protobuf:"bytes,4,opt,name=TxFees,proto3" json:"TxFees,omitempty"`
	BurntFees     []byte                 `protobuf:"bytes,5,opt,name=BurntFees,proto3" json:"BurntFees,omitempty"`
	Uncle         []byte                 `protobuf:"bytes,6,opt,name=Uncle,proto3" json:"Uncle,omitempty"`
	Beneficiary   []byte                 `protobuf:"bytes,7,opt,name=Beneficiary,proto3,oneof" json:"Beneficiary,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinerReward) Reset() {
	*x = MinerReward{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinerReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinerReward) ProtoMessage() {}

func (x *MinerReward) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinerReward.ProtoReflect.Descriptor instead.
func (*MinerReward) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{13}
}

func (x *MinerReward) GetTotal() []byte {
	if x != nil {
		return x.Total
	}
	return nil
}

func (x *MinerReward) GetStatic() []byte {
	if x != nil {
		return x.Static
	}
	return nil
}

func (x *MinerReward) GetDynamic() []byte {
	if x != nil {
		return x.Dynamic
	}
	return nil
}

func (x *MinerReward) GetTxFees() []byte {
	if x != nil {
		return x.TxFees
	}
	return nil
}

func (x *MinerReward) GetBurntFees() []byte {
	if x != nil {
		return x.BurntFees
	}
	return nil
}

func (x *MinerReward) GetUncle() []byte {
	if x != nil {
		return x.Uncle
	}
	return nil
}

func (x *MinerReward) GetBeneficiary() []byte {
	if x != nil {
		return x.Beneficiary
	}
	return nil
}

type ParsedAbiBlockMessage struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Chain         *Chain                  `protobuf:"bytes,1,opt,name=Chain,proto3" json:"Chain,omitempty"`
	Header        *BlockHeader            `protobuf:"bytes,2,opt,name=Header,proto3" json:"Header,omitempty"`
	Uncles        []*BlockHeader          `protobuf:"bytes,3,rep,name=Uncles,proto3" json:"Uncles,omitempty"`
	Reward        *MinerReward            `protobuf:"bytes,4,opt,name=Reward,proto3" json:"Reward,omitempty"`
	UncleRewards  []*MinerReward          `protobuf:"bytes,5,rep,name=UncleRewards,proto3" json:"UncleRewards,omitempty"`
	Transactions  []*ParsedAbiTransaction `protobuf:"bytes,6,rep,name=Transactions,proto3" json:"Transactions,omitempty"`
	L1Header      *BlockHeader            `protobuf:"bytes,7,opt,name=L1Header,proto3,oneof" json:"L1Header,omitempty"`
	ExtraRewards  []*MinerReward          `protobuf:"bytes,8,rep,name=ExtraRewards,proto3" json:"ExtraRewards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParsedAbiBlockMessage) Reset() {
	*x = ParsedAbiBlockMessage{}
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParsedAbiBlockMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParsedAbiBlockMessage) ProtoMessage() {}

func (x *ParsedAbiBlockMessage) ProtoReflect() protoreflect.Message {
	mi := &file_evm_parsed_abi_block_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParsedAbiBlockMessage.ProtoReflect.Descriptor instead.
func (*ParsedAbiBlockMessage) Descriptor() ([]byte, []int) {
	return file_evm_parsed_abi_block_message_proto_rawDescGZIP(), []int{14}
}

func (x *ParsedAbiBlockMessage) GetChain() *Chain {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetHeader() *BlockHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetUncles() []*BlockHeader {
	if x != nil {
		return x.Uncles
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetReward() *MinerReward {
	if x != nil {
		return x.Reward
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetUncleRewards() []*MinerReward {
	if x != nil {
		return x.UncleRewards
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetTransactions() []*ParsedAbiTransaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetL1Header() *BlockHeader {
	if x != nil {
		return x.L1Header
	}
	return nil
}

func (x *ParsedAbiBlockMessage) GetExtraRewards() []*MinerReward {
	if x != nil {
		return x.ExtraRewards
	}
	return nil
}

var File_evm_parsed_abi_block_message_proto protoreflect.FileDescriptor

const file_evm_parsed_abi_block_message_proto_rawDesc = "" +
	"\n" +
	"\"evm/parsed_abi_block_message.proto\x12\fevm_messages\x1a\x17evm/block_message.proto\"\xa4\x02\n" +
	"\rArgumentValue\x12\x12\n" +
	"\x04Type\x18\x01 \x01(\tR\x04Type\x12\x1a\n" +
	"\bIsHashed\x18\x02 \x01(\bR\bIsHashed\x12\x18\n" +
	"\x06String\x18\x03 \x01(\tH\x00R\x06String\x12\x16\n" +
	"\x05Bytes\x18\x04 \x01(\fH\x00R\x05Bytes\x12\x14\n" +
	"\x04UInt\x18\x05 \x01(\x04H\x00R\x04UInt\x12\x12\n" +
	"\x03Int\x18\x06 \x01(\x03H\x00R\x03Int\x12\x14\n" +
	"\x04Bool\x18\a \x01(\bH\x00R\x04Bool\x123\n" +
	"\x05Array\x18\n" +
	" \x01(\v2\x1b.evm_messages.ArgumentArrayH\x00R\x05Array\x123\n" +
	"\x05Tuple\x18\v \x01(\v2\x1b.evm_messages.ArgumentTupleH\x00R\x05TupleB\a\n" +
	"\x05Value\"H\n" +
	"\rArgumentArray\x127\n" +
	"\bElements\x18\x01 \x03(\v2\x1b.evm_messages.ArgumentValueR\bElements\"\\\n" +
	"\rArgumentTuple\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x127\n" +
	"\bElements\x18\x02 \x03(\v2\x1b.evm_messages.ArgumentValueR\bElements\"\xae\x02\n" +
	"\x12ParsedAbiSignature\x12\x16\n" +
	"\x06Parsed\x18\x01 \x01(\bR\x06Parsed\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12\x1c\n" +
	"\tSignature\x18\x03 \x01(\tR\tSignature\x12\x10\n" +
	"\x03Abi\x18\x04 \x01(\tR\x03Abi\x12$\n" +
	"\rSignatureHash\x18\x05 \x01(\fR\rSignatureHash\x12B\n" +
	"\x04Type\x18\x06 \x01(\x0e2..evm_messages.ParsedAbiSignature.SignatureTypeR\x04Type\"R\n" +
	"\rSignatureType\x12\f\n" +
	"\bFUNCTION\x10\x00\x12\x0f\n" +
	"\vCONSTRUCTOR\x10\x01\x12\f\n" +
	"\bFALLBACK\x10\x02\x12\v\n" +
	"\aRECEIVE\x10\x03\x12\a\n" +
	"\x03LOG\x10\x04\"q\n" +
	"\x0eParsedArgument\x12\x12\n" +
	"\x04Name\x18\x01 \x01(\tR\x04Name\x12\x18\n" +
	"\aIndexed\x18\x02 \x01(\bR\aIndexed\x121\n" +
	"\x05Value\x18\x03 \x01(\v2\x1b.evm_messages.ArgumentValueR\x05Value\"\x8c\x02\n" +
	"\x12ParsedAbiLogHeader\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05Index\x12\x1e\n" +
	"\n" +
	"EnterIndex\x18\x02 \x01(\rR\n" +
	"EnterIndex\x12\x1c\n" +
	"\tExitIndex\x18\x03 \x01(\rR\tExitIndex\x12,\n" +
	"\x11LogAfterCallIndex\x18\x04 \x01(\rR\x11LogAfterCallIndex\x12\x0e\n" +
	"\x02Pc\x18\x05 \x01(\x04R\x02Pc\x12$\n" +
	"\rSmartContract\x18\x06 \x01(\fR\rSmartContract\x12>\n" +
	"\tSignature\x18\a \x01(\v2 .evm_messages.ParsedAbiSignatureR\tSignature\"\xe2\x01\n" +
	"\fParsedAbiLog\x12/\n" +
	"\x06Header\x18\x01 \x01(\v2\x17.evm_messages.LogHeaderR\x06Header\x12+\n" +
	"\x06Topics\x18\x02 \x03(\v2\x13.evm_messages.TopicR\x06Topics\x128\n" +
	"\x06Parsed\x18\x03 \x01(\v2 .evm_messages.ParsedAbiLogHeaderR\x06Parsed\x12:\n" +
	"\tArguments\x18\x04 \x03(\v2\x1c.evm_messages.ParsedArgumentR\tArguments\"\xe1\x01\n" +
	"\x11ParsedStateChange\x12\x1e\n" +
	"\n" +
	"EnterIndex\x18\x01 \x01(\rR\n" +
	"EnterIndex\x12\x1c\n" +
	"\tExitIndex\x18\x02 \x01(\rR\tExitIndex\x122\n" +
	"\x14ChangeAfterCallIndex\x18\x03 \x01(\rR\x14ChangeAfterCallIndex\x12\x0e\n" +
	"\x02Pc\x18\x04 \x01(\x04R\x02Pc\x12\x18\n" +
	"\aAddress\x18\x05 \x01(\fR\aAddress\x12\x1a\n" +
	"\bLocation\x18\x06 \x01(\fR\bLocation\x12\x14\n" +
	"\x05Value\x18\a \x01(\fR\x05Value\"\x8b\x05\n" +
	"\x13ParsedAbiCallHeader\x12\x14\n" +
	"\x05Index\x18\x01 \x01(\rR\x05Index\x12\x14\n" +
	"\x05Depth\x18\x02 \x01(\rR\x05Depth\x12\x1e\n" +
	"\n" +
	"EnterIndex\x18\x03 \x01(\rR\n" +
	"EnterIndex\x12\x1c\n" +
	"\tExitIndex\x18\x04 \x01(\rR\tExitIndex\x12 \n" +
	"\vCallerIndex\x18\x05 \x01(\x05R\vCallerIndex\x12$\n" +
	"\rInternalCalls\x18\x06 \x01(\rR\rInternalCalls\x12\x1a\n" +
	"\bCallPath\x18\a \x03(\rR\bCallPath\x12\x12\n" +
	"\x04From\x18\b \x01(\fR\x04From\x12\x0e\n" +
	"\x02To\x18\t \x01(\fR\x02To\x12\x16\n" +
	"\x06Create\x18\n" +
	" \x01(\bR\x06Create\x12\x14\n" +
	"\x05Input\x18\v \x01(\fR\x05Input\x12\x10\n" +
	"\x03Gas\x18\f \x01(\x04R\x03Gas\x12\x14\n" +
	"\x05Value\x18\r \x01(\fR\x05Value\x12\x16\n" +
	"\x06Output\x18\x0e \x01(\fR\x06Output\x12\x18\n" +
	"\aGasUsed\x18\x0f \x01(\x04R\aGasUsed\x12\x14\n" +
	"\x05Error\x18\x10 \x01(\tR\x05Error\x12,\n" +
	"\x06Opcode\x18\x11 \x01(\v2\x14.evm_messages.OpcodeR\x06Opcode\x12\"\n" +
	"\fSelfDestruct\x18\x12 \x01(\bR\fSelfDestruct\x12\x1c\n" +
	"\tDelegated\x18\x13 \x01(\bR\tDelegated\x12\x18\n" +
	"\aSuccess\x18\x14 \x01(\bR\aSuccess\x12\x1a\n" +
	"\bReverted\x18\x15 \x01(\bR\bReverted\x12>\n" +
	"\tSignature\x18\x16 \x01(\v2 .evm_messages.ParsedAbiSignatureR\tSignature\"\xbd\x02\n" +
	"\rParsedAbiCall\x129\n" +
	"\x06Header\x18\x01 \x01(\v2!.evm_messages.ParsedAbiCallHeaderR\x06Header\x12:\n" +
	"\tArguments\x18\x02 \x03(\v2\x1c.evm_messages.ParsedArgumentR\tArguments\x12@\n" +
	"\fReturnValues\x18\x03 \x03(\v2\x1c.evm_messages.ParsedArgumentR\fReturnValues\x12.\n" +
	"\x04Logs\x18\x04 \x03(\v2\x1a.evm_messages.ParsedAbiLogR\x04Logs\x12C\n" +
	"\fStateChanges\x18\x05 \x03(\v2\x1f.evm_messages.ParsedStateChangeR\fStateChanges\"\xfa\x01\n" +
	"\x0eTransactionFee\x12\x1c\n" +
	"\tSenderFee\x18\x01 \x01(\fR\tSenderFee\x12,\n" +
	"\x11PriorityFeePerGas\x18\x02 \x01(\fR\x11PriorityFeePerGas\x12,\n" +
	"\x11EffectiveGasPrice\x18\x03 \x01(\fR\x11EffectiveGasPrice\x12\x1c\n" +
	"\tGasRefund\x18\x04 \x01(\x04R\tGasRefund\x12\x14\n" +
	"\x05Burnt\x18\x05 \x01(\fR\x05Burnt\x12\x18\n" +
	"\aSavings\x18\x06 \x01(\fR\aSavings\x12 \n" +
	"\vMinerReward\x18\a \x01(\fR\vMinerReward\"r\n" +
	"\x1aParsedAbiTransactionStatus\x12\x18\n" +
	"\aSuccess\x18\x01 \x01(\bR\aSuccess\x12\x1a\n" +
	"\bEndError\x18\x02 \x01(\tR\bEndError\x12\x1e\n" +
	"\n" +
	"FaultError\x18\x03 \x01(\tR\n" +
	"FaultError\"\xa0\x05\n" +
	"\x14ParsedAbiTransaction\x12M\n" +
	"\x11TransactionHeader\x18\x01 \x01(\v2\x1f.evm_messages.TransactionHeaderR\x11TransactionHeader\x12A\n" +
	"\rReceiptHeader\x18\x02 \x01(\v2\x1b.evm_messages.ReceiptHeaderR\rReceiptHeader\x12D\n" +
	"\x0eTransactionFee\x18\x03 \x01(\v2\x1c.evm_messages.TransactionFeeR\x0eTransactionFee\x12V\n" +
	"\x11TransactionStatus\x18\x04 \x01(\v2(.evm_messages.ParsedAbiTransactionStatusR\x11TransactionStatus\x121\n" +
	"\x05Calls\x18\x05 \x03(\v2\x1b.evm_messages.ParsedAbiCallR\x05Calls\x125\n" +
	"\tSignature\x18\x06 \x01(\v2\x17.evm_messages.SignatureR\tSignature\x12R\n" +
	"\x13TokenBalanceUpdates\x18\a \x03(\v2 .evm_messages.TokenBalanceUpdateR\x13TokenBalanceUpdates\x12U\n" +
	"\x14NativeBalanceUpdates\x18\b \x03(\v2!.evm_messages.NativeBalanceUpdateR\x14NativeBalanceUpdates\x12C\n" +
	"\x0eStorageChanges\x18\t \x03(\v2\x1b.evm_messages.StorageChangeR\x0eStorageChanges\"\xd8\x01\n" +
	"\vMinerReward\x12\x14\n" +
	"\x05Total\x18\x01 \x01(\fR\x05Total\x12\x16\n" +
	"\x06Static\x18\x02 \x01(\fR\x06Static\x12\x18\n" +
	"\aDynamic\x18\x03 \x01(\fR\aDynamic\x12\x16\n" +
	"\x06TxFees\x18\x04 \x01(\fR\x06TxFees\x12\x1c\n" +
	"\tBurntFees\x18\x05 \x01(\fR\tBurntFees\x12\x14\n" +
	"\x05Uncle\x18\x06 \x01(\fR\x05Uncle\x12%\n" +
	"\vBeneficiary\x18\a \x01(\fH\x00R\vBeneficiary\x88\x01\x01B\x0e\n" +
	"\f_Beneficiary\"\xea\x03\n" +
	"\x15ParsedAbiBlockMessage\x12)\n" +
	"\x05Chain\x18\x01 \x01(\v2\x13.evm_messages.ChainR\x05Chain\x121\n" +
	"\x06Header\x18\x02 \x01(\v2\x19.evm_messages.BlockHeaderR\x06Header\x121\n" +
	"\x06Uncles\x18\x03 \x03(\v2\x19.evm_messages.BlockHeaderR\x06Uncles\x121\n" +
	"\x06Reward\x18\x04 \x01(\v2\x19.evm_messages.MinerRewardR\x06Reward\x12=\n" +
	"\fUncleRewards\x18\x05 \x03(\v2\x19.evm_messages.MinerRewardR\fUncleRewards\x12F\n" +
	"\fTransactions\x18\x06 \x03(\v2\".evm_messages.ParsedAbiTransactionR\fTransactions\x12:\n" +
	"\bL1Header\x18\a \x01(\v2\x19.evm_messages.BlockHeaderH\x00R\bL1Header\x88\x01\x01\x12=\n" +
	"\fExtraRewards\x18\b \x03(\v2\x19.evm_messages.MinerRewardR\fExtraRewardsB\v\n" +
	"\t_L1Headerb\x06proto3"

var (
	file_evm_parsed_abi_block_message_proto_rawDescOnce sync.Once
	file_evm_parsed_abi_block_message_proto_rawDescData []byte
)

func file_evm_parsed_abi_block_message_proto_rawDescGZIP() []byte {
	file_evm_parsed_abi_block_message_proto_rawDescOnce.Do(func() {
		file_evm_parsed_abi_block_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_evm_parsed_abi_block_message_proto_rawDesc), len(file_evm_parsed_abi_block_message_proto_rawDesc)))
	})
	return file_evm_parsed_abi_block_message_proto_rawDescData
}

var file_evm_parsed_abi_block_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_evm_parsed_abi_block_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_evm_parsed_abi_block_message_proto_goTypes = []any{
	(ParsedAbiSignature_SignatureType)(0), // 0: evm_messages.ParsedAbiSignature.SignatureType
	(*ArgumentValue)(nil),                 // 1: evm_messages.ArgumentValue
	(*ArgumentArray)(nil),                 // 2: evm_messages.ArgumentArray
	(*ArgumentTuple)(nil),                 // 3: evm_messages.ArgumentTuple
	(*ParsedAbiSignature)(nil),            // 4: evm_messages.ParsedAbiSignature
	(*ParsedArgument)(nil),                // 5: evm_messages.ParsedArgument
	(*ParsedAbiLogHeader)(nil),            // 6: evm_messages.ParsedAbiLogHeader
	(*ParsedAbiLog)(nil),                  // 7: evm_messages.ParsedAbiLog
	(*ParsedStateChange)(nil),             // 8: evm_messages.ParsedStateChange
	(*ParsedAbiCallHeader)(nil),           // 9: evm_messages.ParsedAbiCallHeader
	(*ParsedAbiCall)(nil),                 // 10: evm_messages.ParsedAbiCall
	(*TransactionFee)(nil),                // 11: evm_messages.TransactionFee
	(*ParsedAbiTransactionStatus)(nil),    // 12: evm_messages.ParsedAbiTransactionStatus
	(*ParsedAbiTransaction)(nil),          // 13: evm_messages.ParsedAbiTransaction
	(*MinerReward)(nil),                   // 14: evm_messages.MinerReward
	(*ParsedAbiBlockMessage)(nil),         // 15: evm_messages.ParsedAbiBlockMessage
	(*LogHeader)(nil),                     // 16: evm_messages.LogHeader
	(*Topic)(nil),                         // 17: evm_messages.Topic
	(*Opcode)(nil),                        // 18: evm_messages.Opcode
	(*TransactionHeader)(nil),             // 19: evm_messages.TransactionHeader
	(*ReceiptHeader)(nil),                 // 20: evm_messages.ReceiptHeader
	(*Signature)(nil),                     // 21: evm_messages.Signature
	(*TokenBalanceUpdate)(nil),            // 22: evm_messages.TokenBalanceUpdate
	(*NativeBalanceUpdate)(nil),           // 23: evm_messages.NativeBalanceUpdate
	(*StorageChange)(nil),                 // 24: evm_messages.StorageChange
	(*Chain)(nil),                         // 25: evm_messages.Chain
	(*BlockHeader)(nil),                   // 26: evm_messages.BlockHeader
}
var file_evm_parsed_abi_block_message_proto_depIdxs = []int32{
	2,  // 0: evm_messages.ArgumentValue.Array:type_name -> evm_messages.ArgumentArray
	3,  // 1: evm_messages.ArgumentValue.Tuple:type_name -> evm_messages.ArgumentTuple
	1,  // 2: evm_messages.ArgumentArray.Elements:type_name -> evm_messages.ArgumentValue
	1,  // 3: evm_messages.ArgumentTuple.Elements:type_name -> evm_messages.ArgumentValue
	0,  // 4: evm_messages.ParsedAbiSignature.Type:type_name -> evm_messages.ParsedAbiSignature.SignatureType
	1,  // 5: evm_messages.ParsedArgument.Value:type_name -> evm_messages.ArgumentValue
	4,  // 6: evm_messages.ParsedAbiLogHeader.Signature:type_name -> evm_messages.ParsedAbiSignature
	16, // 7: evm_messages.ParsedAbiLog.Header:type_name -> evm_messages.LogHeader
	17, // 8: evm_messages.ParsedAbiLog.Topics:type_name -> evm_messages.Topic
	6,  // 9: evm_messages.ParsedAbiLog.Parsed:type_name -> evm_messages.ParsedAbiLogHeader
	5,  // 10: evm_messages.ParsedAbiLog.Arguments:type_name -> evm_messages.ParsedArgument
	18, // 11: evm_messages.ParsedAbiCallHeader.Opcode:type_name -> evm_messages.Opcode
	4,  // 12: evm_messages.ParsedAbiCallHeader.Signature:type_name -> evm_messages.ParsedAbiSignature
	9,  // 13: evm_messages.ParsedAbiCall.Header:type_name -> evm_messages.ParsedAbiCallHeader
	5,  // 14: evm_messages.ParsedAbiCall.Arguments:type_name -> evm_messages.ParsedArgument
	5,  // 15: evm_messages.ParsedAbiCall.ReturnValues:type_name -> evm_messages.ParsedArgument
	7,  // 16: evm_messages.ParsedAbiCall.Logs:type_name -> evm_messages.ParsedAbiLog
	8,  // 17: evm_messages.ParsedAbiCall.StateChanges:type_name -> evm_messages.ParsedStateChange
	19, // 18: evm_messages.ParsedAbiTransaction.TransactionHeader:type_name -> evm_messages.TransactionHeader
	20, // 19: evm_messages.ParsedAbiTransaction.ReceiptHeader:type_name -> evm_messages.ReceiptHeader
	11, // 20: evm_messages.ParsedAbiTransaction.TransactionFee:type_name -> evm_messages.TransactionFee
	12, // 21: evm_messages.ParsedAbiTransaction.TransactionStatus:type_name -> evm_messages.ParsedAbiTransactionStatus
	10, // 22: evm_messages.ParsedAbiTransaction.Calls:type_name -> evm_messages.ParsedAbiCall
	21, // 23: evm_messages.ParsedAbiTransaction.Signature:type_name -> evm_messages.Signature
	22, // 24: evm_messages.ParsedAbiTransaction.TokenBalanceUpdates:type_name -> evm_messages.TokenBalanceUpdate
	23, // 25: evm_messages.ParsedAbiTransaction.NativeBalanceUpdates:type_name -> evm_messages.NativeBalanceUpdate
	24, // 26: evm_messages.ParsedAbiTransaction.StorageChanges:type_name -> evm_messages.StorageChange
	25, // 27: evm_messages.ParsedAbiBlockMessage.Chain:type_name -> evm_messages.Chain
	26, // 28: evm_messages.ParsedAbiBlockMessage.Header:type_name -> evm_messages.BlockHeader
	26, // 29: evm_messages.ParsedAbiBlockMessage.Uncles:type_name -> evm_messages.BlockHeader
	14, // 30: evm_messages.ParsedAbiBlockMessage.Reward:type_name -> evm_messages.MinerReward
	14, // 31: evm_messages.ParsedAbiBlockMessage.UncleRewards:type_name -> evm_messages.MinerReward
	13, // 32: evm_messages.ParsedAbiBlockMessage.Transactions:type_name -> evm_messages.ParsedAbiTransaction
	26, // 33: evm_messages.ParsedAbiBlockMessage.L1Header:type_name -> evm_messages.BlockHeader
	14, // 34: evm_messages.ParsedAbiBlockMessage.ExtraRewards:type_name -> evm_messages.MinerReward
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_evm_parsed_abi_block_message_proto_init() }
func file_evm_parsed_abi_block_message_proto_init() {
	if File_evm_parsed_abi_block_message_proto != nil {
		return
	}
	file_evm_block_message_proto_init()
	file_evm_parsed_abi_block_message_proto_msgTypes[0].OneofWrappers = []any{
		(*ArgumentValue_String_)(nil),
		(*ArgumentValue_Bytes)(nil),
		(*ArgumentValue_UInt)(nil),
		(*ArgumentValue_Int)(nil),
		(*ArgumentValue_Bool)(nil),
		(*ArgumentValue_Array)(nil),
		(*ArgumentValue_Tuple)(nil),
	}
	file_evm_parsed_abi_block_message_proto_msgTypes[13].OneofWrappers = []any{}
	file_evm_parsed_abi_block_message_proto_msgTypes[14].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_evm_parsed_abi_block_message_proto_rawDesc), len(file_evm_parsed_abi_block_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_evm_parsed_abi_block_message_proto_goTypes,
		DependencyIndexes: file_evm_parsed_abi_block_message_proto_depIdxs,
		EnumInfos:         file_evm_parsed_abi_block_message_proto_enumTypes,
		MessageInfos:      file_evm_parsed_abi_block_message_proto_msgTypes,
	}.Build()
	File_evm_parsed_abi_block_message_proto = out.File
	file_evm_parsed_abi_block_message_proto_goTypes = nil
	file_evm_parsed_abi_block_message_proto_depIdxs = nil
}
