# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solana/corecast/corecast.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'solana/corecast/corecast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from solana.corecast import request_pb2 as solana_dot_corecast_dot_request__pb2
from solana.corecast import stream_message_pb2 as solana_dot_corecast_dot_stream__message__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1esolana/corecast/corecast.proto\x12\x0fsolana_corecast\x1a\x1dsolana/corecast/request.proto\x1a$solana/corecast/stream_message.proto2\xf3\x04\n\x08\x43oreCast\x12^\n\tDexTrades\x12\'.solana_corecast.SubscribeTradesRequest\x1a&.solana_corecast.DexTradeStreamMessage0\x01\x12^\n\tDexOrders\x12\'.solana_corecast.SubscribeOrdersRequest\x1a&.solana_corecast.DexOrderStreamMessage0\x01\x12g\n\x08\x44\x65xPools\x12&.solana_corecast.SubscribePoolsRequest\x1a\x31.solana_corecast.PoolLiquidityChangeStreamMessage0\x01\x12p\n\x0cTransactions\x12-.solana_corecast.SubscribeTransactionsRequest\x1a/.solana_corecast.ParsedTransactionStreamMessage0\x01\x12\x61\n\tTransfers\x12*.solana_corecast.SubscribeTransfersRequest\x1a&.solana_corecast.TransferStreamMessage0\x01\x12i\n\x08\x42\x61lances\x12..solana_corecast.SubscribeBalanceUpdateRequest\x1a+.solana_corecast.BalanceUpdateStreamMessage0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solana.corecast.corecast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CORECAST']._serialized_start=121
  _globals['_CORECAST']._serialized_end=748
# @@protoc_insertion_point(module_scope)
