# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: solana/corecast/request.proto
# Protobuf Python Version: 6.32.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    32,
    0,
    '',
    'solana/corecast/request.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dsolana/corecast/request.proto\x12\x0fsolana_corecast\"\xd6\x01\n\x16SubscribeTradesRequest\x12/\n\x07program\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12,\n\x04pool\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12-\n\x05token\x18\x03 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12.\n\x06trader\x18\x04 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\xd6\x01\n\x16SubscribeOrdersRequest\x12/\n\x07program\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12,\n\x04pool\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12-\n\x05token\x18\x03 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12.\n\x06trader\x18\x04 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\xa5\x01\n\x15SubscribePoolsRequest\x12/\n\x07program\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12,\n\x04pool\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12-\n\x05token\x18\x03 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\x7f\n\x1cSubscribeTransactionsRequest\x12/\n\x07program\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12.\n\x06signer\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\xac\x01\n\x19SubscribeTransfersRequest\x12.\n\x06sender\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12\x30\n\x08receiver\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12-\n\x05token\x18\x03 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\x7f\n\x1dSubscribeBalanceUpdateRequest\x12/\n\x07\x61\x64\x64ress\x18\x01 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\x12-\n\x05token\x18\x02 \x01(\x0b\x32\x1e.solana_corecast.AddressFilter\"\"\n\rAddressFilter\x12\x11\n\taddresses\x18\x01 \x03(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solana.corecast.request_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBSCRIBETRADESREQUEST']._serialized_start=51
  _globals['_SUBSCRIBETRADESREQUEST']._serialized_end=265
  _globals['_SUBSCRIBEORDERSREQUEST']._serialized_start=268
  _globals['_SUBSCRIBEORDERSREQUEST']._serialized_end=482
  _globals['_SUBSCRIBEPOOLSREQUEST']._serialized_start=485
  _globals['_SUBSCRIBEPOOLSREQUEST']._serialized_end=650
  _globals['_SUBSCRIBETRANSACTIONSREQUEST']._serialized_start=652
  _globals['_SUBSCRIBETRANSACTIONSREQUEST']._serialized_end=779
  _globals['_SUBSCRIBETRANSFERSREQUEST']._serialized_start=782
  _globals['_SUBSCRIBETRANSFERSREQUEST']._serialized_end=954
  _globals['_SUBSCRIBEBALANCEUPDATEREQUEST']._serialized_start=956
  _globals['_SUBSCRIBEBALANCEUPDATEREQUEST']._serialized_end=1083
  _globals['_ADDRESSFILTER']._serialized_start=1085
  _globals['_ADDRESSFILTER']._serialized_end=1119
# @@protoc_insertion_point(module_scope)
